### ISSUE TITLE
black screen on startup

### ISSUE THREAD

**Issue by salcin** [gmc-holle/xfdashboard#100]
Hi,

I don't have any problems during the compiled on my Debian testing but when i will run xfdashboard from a terminal I get a black screen.

The cause of the problem can it come from my dual screen ?

Thank you for your help.

Here is the log output :

$ xfdashboard -d
xfdashboard-Message: Setting deprecated property 'unmapped-window-icon-gravity' at XfdashboardWindowContent, use 'unmapped-window-icon-anchor-point' instead
xfdashboard-Message: Setting deprecated property 'unmapped-window-icon-gravity' at XfdashboardWindowContent, use 'unmapped-window-icon-anchor-point' instead
xfdashboard-Message: Setting deprecated property 'unmapped-window-icon-gravity' at XfdashboardWindowContent, use 'unmapped-window-icon-anchor-point' instead

(xfdashboard:3610): Cogl-WARNING **: Shader compilation failed:
Vertex shader failed to compile with the following errors:
ERROR: error(#271) Explicit version number 120 not supported by GL3 forward compatible context
ERROR: error(#273) 1 compilation errors.  No code generated

(xfdashboard:3610): Cogl-WARNING **: Shader compilation failed:
Fragment shader failed to compile with the following errors:
ERROR: error(#271) Explicit version number 120 not supported by GL3 forward compatible context
ERROR: error(#273) 1 compilation errors.  No code generated

(xfdashboard:3610): Cogl-WARNING **: Failed to link GLSL program:
Vertex and Fragment shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed.   

(xfdashboard:3610): Cogl-WARNING **: driver/gl/cogl-pipeline-progend-glsl.c:796: GL error (1282): Invalid operation

(xfdashboard:3610): Cogl-WARNING **: driver/gl/cogl-pipeline-progend-glsl.c:819: GL error (1282): Invalid operation

(xfdashboard:3610): Cogl-WARNING **: driver/gl/cogl-pipeline-progend-glsl.c:823: GL error (1282): Invalid operation

**Comment by gmc-holle** [comment]
Tthis should be no problem of xfdashboard but it looks like your graphics card driver isn't working properly and does not support OpenGL features expected and needed by Clutter and Cogl. Please check that you have installed and enabled the correct driver for your graphics card. At first step I would execute the following command in a terminal:

```
glxinfo | egrep -i '^[a-z]+'
```
