### ISSUE TITLE
Another openSUSE compiler check ­— 64bit-portability-issue

### ISSUE THREAD

**Issue by DAP-DarkneSS** [gmc-holle/xfdashboard#101]
openSUSE Tumbleweed, gcc 5, glib 2.38.2.

Build log:
[  315s] quicklaunch.c: In function
'_xfdashboard_quicklaunch_get_actor_for_appinfo':
[  315s] /usr/include/glib-2.0/glib/gmessages.h:382:10: warning: return
makes pointer from integer without a cast [-Wint-conversion]
[  315s]    return (val);       \
[  315s]           ^
[  315s] quicklaunch.c:161:2: note: in expansion of macro
'g_return_val_if_fail'
[  315s]   g_return_val_if_fail(XFDASHBOARD_IS_QUICKLAUNCH(self), TRUE);
[  315s]   ^
[  315s] /usr/include/glib-2.0/glib/gmessages.h:382:10: warning: return
makes pointer from integer without a cast [-Wint-conversion]
[  315s]    return (val);       \
[  315s]           ^
[  315s] quicklaunch.c:162:2: note: in expansion of macro
'g_return_val_if_fail'
[  315s]   g_return_val_if_fail(G_IS_APP_INFO(inAppInfo), TRUE);
[  315s]   ^
 
 
This is the function:
 >  151 /* Get actor for desktop application information */
>  152 static ClutterActor* _xfdashboard_quicklaunch_get_actor_for_appinfo(XfdashboardQuicklaunch *self,
>  153                                                                                                                                              GAppInfo *inAppInfo)
>  154 {
>  155         XfdashboardQuicklaunchPrivate   *priv;
>  156         ClutterActorIter                                iter;
>  157         ClutterActor                                    *child;
>  158         GAppInfo                                                *desktopAppInfo;
>  159         GFile                                                   *desktopFile;
>  160 
>  161         g_return_val_if_fail(XFDASHBOARD_IS_QUICKLAUNCH(self), TRUE);
>  162         g_return_val_if_fail(G_IS_APP_INFO(inAppInfo), TRUE);
 
Now the "g_return_val_if_fail" macro will return TRUE if the condition
is false. But the return value of the function is "ClutterActor*", so
maybe returning NULL would be better, but I cannot tell for sure, I'm
not familiar with the code.

Please read opensuse-factory mailing list archive: http://lists.opensuse.org/opensuse-factory/2015-11/msg00137.html

Feel free to: write there, make me write there, fix it, ignore it :)

**Comment by gmc-holle** [comment]
Hi,

I already saw the discussion on the mailing list and I fixed it yesterday because it was wrong ;)

See commit aa3dc1bcb3fe6f9ff6b10c65a5b74e4198233515 (it's only at http://git.xfce.org/apps/xfdashboard currently - problems with pushing to this repository :( )

Regards

**Comment by gmc-holle** [comment]
I could fix my problem with pushing to Github :)

Commit aa3dc1bcb3fe6f9ff6b10c65a5b74e4198233515 is now available here
