### ISSUE TITLE
Implement button to perform certain actions like exit from application

### ISSUE THREAD

**Issue by axeoth** [gmc-holle/xfdashboard#102]
Often, I need to access an icon from the desktop. To do this, I start xfdashboard, then use the mouse roll to go to an empty desktop, then click on the empty desktop (the bar on the right).

The equivalent way would be to press "ESC" while above an empty desktop.

However, it would be nice to do this simply by clicking the empty desktop in the center of the screen, or to provide a button on the dashboard for it, or other.

**Comment by gmc-holle** [comment]
I don't know if I understand your request correctly. By pressing an empty space in the center of the screen could exit from xfdashboard but you would end up on your desktop with all your windows open (as it was before). So you have again to find an empty desktop to get access to your icons.

Or did I miss the spot - the difference from your approach?

**Comment by axeoth** [comment]
Hi,

 Thanks for replying so fast. Actually, if I press "ESC" in exactly the same configuration, what I obtain is the current (and accidentally, empty) desktop. I am not sure that xfdashboard will go back to the initial desktop, as it doesn't do it if I press "ESC" (which, I assume, exits).

 Just launch xfdashboard, go above (mouse scroll) an empty desktop, and press "ESC". Now, all that it is missing is a way to do the same with the mouse only.

 Maybe my "ESC" key is bound to something else, though.

Thanks.

**Comment by gmc-holle** [comment]
And what about clicking on an empty workspace (on the right) with the mouse? Does it not work or is it not the "workaround" you are looking for?

You do not need to scroll through the workspaces with the mouse wheel to select a workspace. You can just click it to select and activate it. Activating a workspace this way will also exit from xfdashboard.


-------- Ursprüngliche Nachricht --------
Von: axeoth <notifications@github.com>
Gesendet: 30. November 2015 21:57:45 MEZ
An: gmc-holle/xfdashboard <xfdashboard@noreply.github.com>
CC: gmc-holle <nomad@froevel.de>
Betreff: Re: [xfdashboard] "Go to current empty desktop" using the mouse only (#102)

Hi,

 Thanks for replying so fast. Actually, if I press "ESC" in exactly the same configuration, what I obtain is the current (and accidentally, empty) desktop. I am not sure that xfdashboard will go back to the initial desktop, as it doesn't do it if I press "ESC" (which, I assume, exits).

 Just launch xfdashboard, go above (mouse scroll) an empty desktop, and press "ESC". Now, all that it is missing is a way to do the same with the mouse only.

 Maybe my "ESC" key is bound to something else, though.

Thanks.

---

**Comment by axeoth** [comment]
It works, but it is less practical to go from the upper left corner (where xfdashboard gets activated) to the right workspaces bar. It makes the mouse scroll less practical because you still need to go to the bar.

There is another use case: clicking on a special-designated area (could be a button next to the Windows/Applications buttons or even a shortcut on the left dashboard) to reload the current workspace "as it was" for quick switching between workspaces without always need to look for "the window that I was working in" in order to click on it.

Often, I just need to copy something from an window in the workspace below into the window in the workspace above. Both windows are "by default" current in each workspace.

**Comment by axeoth** [comment]
Just for the record, pressing "ESC" covers excellently the both use cases, but one still needs to reach for the keyboard. Basically a dashboard-button or a special button somewhere in xfdashboard with the meaning of "ESC" that is, as far as I understand, "exit".

**Comment by gmc-holle** [comment]
I'm sorry but xfdashboard does behave as intended. But I think I understood. You would like to exit from application with just a mouse click without selecting anything like a window or a workspace. Ideally xfdashboard would provide an "x" button you can click. So that there is no need to use the keyboard.

Currently there is nothing implemented you can use to do what you want. What I can do and what my first idea is to provide some kind of action button which can used multiple times and configured for some actions like exiting from xfdashboard. But I would not include it in the default theme but it would be available for custom themes.

My first idea would need you to add a XfdashboardActionButton to the layout, e.g. like this:

```
<object class="XfdashboardActionButton">
    <property name="action">application.quit</property>
</object>
```

I could also add more action like move focus to next focusable actor so that you don't need to press <TAB> anymore and so on ;)

What do you think?

**Comment by axeoth** [comment]
Hi and thanks. Indeed, xfdashboard is behaving as intended, the issue was not meant to report a bug, but to ask for a new functionality. I fully agree with your interpretation and your proposed solution (assuming that the application.quit is the behavior behind the current "ESC" key). You will decide about the place of such button, I was thinking about the place at the left of the top search textbox, but anywhere around that area (I trigger xfdashboard with the mouse in the upper-left corner by using the HotCorner xfce plugin) would be fine, to minimize mouse gestures.

Thanks++

**Comment by axeoth** [comment]
*Or on the dashboard, below of the current "Applications/Windows" (aka "House") button.

**Comment by gmc-holle** [comment]
No problem. That's an enhancement (or a new functionality) that should be done easily but not in short time.

As I mentioned before I would not include it into the default theme. But I can provide a (nearly) "mouse-only" theme for this new function. But don't expect it anytime soon as I have been busy for some time now.

**Comment by axeoth** [comment]
Thank you. Take your time, it is me and the rest of user community that are grateful for your work. It would be nice to also have the option in xfdashboard-settings that, when switching workspaces with the mouse wheel, the position of the mouse to be irrelevant (currently, it only works if the mouse is over the large "curent workspace" area.

**Comment by gmc-holle** [comment]
To make it easier for me to keep track of single issues/enhancements/etc., could you please open another fresh issue for you last request?

**Comment by axeoth** [comment]
Done. Thank you, once again.

**Comment by gmc-holle** [comment]
Implemented with commit d41a71837e20dbd6ea70214bc94a3152fc456370

To test the new XfdashboardActionButton to perform certain actions you can download a test theme at http://xfdashboard.froevel.de/downloads/action-button-test-theme-0.0.1.tar.bz2, extract it to *$HOME/.theme* and select it in xfdashboard settings dialog.

The test theme will add a button with an "exit" icon left to the view selector which will quit the application when clicked.

Feel free to re-open this issue when you discover problems or if you have questions regarding the implementation and how to use it.

**Comment by axeoth** [comment]
Hey, it works! Many thanks! Apparently, it must be copied into .themes (with "s"). Any chance to have this theme distributed along the existing ones? Something like "xfdashboard-richer" or similar.

**Comment by gmc-holle** [comment]
Sorry for missing the 's' in .themes :(

Honestly I have already some themes to manage and these are even not created by me. In addition this test theme for this new actor class does not look nice and is even uglier than the default theme. So I would like **not** to include it as a standard theme.

It is and maybe be will a dream to get a beautiful looking theme which could replace the current default one :/ Then we could think about integrating a "close" button to it.

**Comment by axeoth** [comment]
Thank you. To be honest, I like (and use) the default theme, I do not really see why it is "ugly". I like it. Well, tastes... :)

**Comment by axeoth** [comment]
Could you please re-upload the following test theme?

http://xfdashboard.froevel.de/downloads/action-button-test-theme-0.0.1.tar.bz2

The link no longer works and I somehow discarded the originally downloaded file. I apologize.

**Comment by gmc-holle** [comment]
Sorry, I don't have this file anymore either but I can tell you what to do ;)

Just copy the default xfdashboard theme from /usr/share/themes/xfdashboard/ to $HOME/.themes/action-button-test-theme and apply the following patch to the file `$HOME/.themes/action-button-test-theme/xfdashboard-1.0/xfdashboard.xml`:

```
--- xfdashboard-1.0/xfdashboard.xml	2016-12-29 16:30:45.925925765 +0100
+++ xfdashboard-1.0/xfdashboard.xml	2016-01-24 13:37:53.833989476 +0100
@@ -64,15 +64,6 @@
 								</layout>
 
 								<child>
-									<object class="XfdashboardActionButton">
-										<property name="button-style">icon</property>
-										<property name="icon-name">exit</property>
-										<property name="target">XfdashboardApplication</property>
-										<property name="action">exit</property>
-									</object>
-								</child>
-
-								<child>
 									<object class="XfdashboardViewSelector" id="view-selector">
 										<property name="viewpad" ref="viewpad"></property>
 									</object>
´´´

Do not forget to activate this new theme in xfdashboard settings.

**Comment by userxfce** [comment]
Hey. The patch is reversed, but a -R solves that. Many thanks.

**Comment by userxfce** [comment]
> Sorry, I don't have this file anymore either but I can tell you what to do ;)
> 
> Just copy the default xfdashboard theme from /usr/share/themes/xfdashboard/ to $HOME/.themes/action-button-test-theme and apply the following patch to the file `$HOME/.themes/action-button-test-theme/xfdashboard-1.0/xfdashboard.xml`:
> 
> ```
> --- xfdashboard-1.0/xfdashboard.xml	2016-12-29 16:30:45.925925765 +0100
> +++ xfdashboard-1.0/xfdashboard.xml	2016-01-24 13:37:53.833989476 +0100
> @@ -64,15 +64,6 @@
>  								</layout>
>  
>  								<child>
> -									<object class="XfdashboardActionButton">
> -										<property name="button-style">icon</property>
> -										<property name="icon-name">exit</property>
> -										<property name="target">XfdashboardApplication</property>
> -										<property name="action">exit</property>
> -									</object>
> -								</child>
> -
> -								<child>
>  									<object class="XfdashboardViewSelector" id="view-selector">
>  										<property name="viewpad" ref="viewpad"></property>
>  									</object>
> ```
> 
> Do not forget to activate this new theme in xfdashboard settings.

Hi,

 The above instructions no longer work under xfdashboard 1.0, I think. Maybe because the layouts of the files/themes have changed. Would you please be so kind as to provide an update? Thank you in advance!
