### ISSUE TITLE
Allow mouse wheel changes workspace in Windows View for all mouse positions

### ISSUE THREAD

**Issue by axeoth** [gmc-holle/xfdashboard#103]
Currently, when the option "Mouse wheel changes workspace" is activated under "Windows view" in xfdashboard-settings, one can use the mouse wheel to change among existing workspaces when in Windows View.

However, for this to work, the mouse has to be over the central area where the windows (if any) in the current workspace are displayed. This is less practical when one wishes to quickly change workspaces while the mouse is still in the screen corner, a popular mouse shortcut to trigger xfdashboard "Windows view" mode.

Enhancement: allow, possibly through an option in xfdashboard-settings, that "Mouse wheel changes workspace" work for all mouse pointer positions (including the corners).

**Comment by gmc-holle** [comment]
Makes sense that mouse wheel will work "everywhere" to change workspace when this option is enabled.

My idea would be that the mouse wheel will change workspace when ...
a) the windows view is active
b) the mouse wheel is not handled by the actor under the pointer

Sadly my first attempt did not work. But I keep trying.

**Comment by gmc-holle** [comment]
Second attempt and success :) See commit 9a6db0999754e1c2ab872874ba0c41a74ddf0f05

Feel free to test this implementation in current git if familiar with git

Closing this issue. Please re-open if it does not work or if you have any other issues with this implementation.

**Comment by axeoth** [comment]
Hey, I am glad to confirm that it works as intended. Thanks!

**Comment by axeoth** [comment]
I do not know if that's related, but I had to uncomment in the xfdashboard/Makefile (after running autogen.sh) the enums.c, enums.h, marshal.c, marshal.h targets, and to "make enums.c" and the others manually before succeding into compiling xfdashboard. Unsure if that's the right way to do it, that's why I am writing it here.

Other than that, it works OK.

**Comment by gmc-holle** [comment]
First at all I'm glad that it works. Mission accomplished ;)

Regarding you compiling issues: It doesn't happen to me and I'm not sure what is going wrong. I have to say that I'm a noob when it is about autotools. I just search for code snippets and adopt them and it went well so far. The only thing I knew that the maintainer mode has to be active (and should be by default when compiling code from git and not from tarballs) to get enum.{c,h} and marshal.{c,h} compiled. Maybe you should try to add "--enable-maintainer-mode" to autogen.sh as parameter? But I'm not really sure :(

**Comment by axeoth** [comment]
Hey, it did work, except that it is not to ./autogen.sh, but to ./configure script that the option has to be passed:

./configure --prefix=/opt/xfdashboard-master --enable-maintainer-mode

(the --prefix option is where xfdashboard will be installed).

 Great and thanks!

**Comment by gmc-holle** [comment]
Strange. It works for me to add the parameter to ./autogen.sh which passes it to ./configure automatically.

But at the end it is the result that counts - it works :)

**Comment by axeoth** [comment]
Hey, you are right, it works both ways. I must have typed something wrong back then. Thanks again.
