### ISSUE TITLE
Sort icons by most used

### ISSUE THREAD

**Issue by newbieg** [gmc-holle/xfdashboard#106]
I'm just hoping for something a bit more intuitive in the way that app-icons appear during a search, I'm hoping for them to be sorted with the most used (or at least most clicked-on) apps appearing at the top of the dash with focus. This would allow me to type "ter" in the search and hit enter without even looking and know that my favourite terminal emulator will be selected. 
Some of the results for me would be:
cal would equal calibre instead of calculator
term would be terminal instead of "preferred applications" (it has terminal listed in its description)
file would be nemo instead of archive file manager.
etc.

I'm otherwise loving xfdashboard, it's been a big comfort since moving out of the gnome environment.

**Comment by gmc-holle** [comment]
Hi,

Thanks for loving xfdashboard :D and thanks for your advice how to improve it. I think it may be possible to count the clicks on each application icon regardless if it was clicked in the quicklaunch or in the search view. And if I could count the clicks and can use them to calculate the relevance of each application found and sort them by relevance. So .... yes, I like this idea :)

Sadly the roadmap is full of smaller and larger issues, enhancements etc. It will take some time. I hope I can implement it since the next stable version 0.6.0.

**Comment by newbieg** [comment]
Thank you, I'm looking forward to it. I took a peak at the code today to try to guess how hard it would be. My only coding experience is in c++ and java, so GObjects and gtk++ look very intimidating.

**Comment by gmc-holle** [comment]
I thought about it and I know how I store the information and how to use them in the application search provider. But the question is: How smart should it be?

I have three option:

1.) Count each click in applications results only and reuse this counter to calculate the relevance.
2.) Count each click on any widget starting an application. That means to count also clicks on icons in quicklauch etc.
3.) xfdashboard supports sending the signal "Launched" on "org.gtk.gio.DesktopAppInfo" just like the object GDesktopAppInfo of Glib does. We could count these signals and use this counter to calculate the relevance. Doing this could also consider applications not only launched by xfdashboard but also of any other application sending this signal. As far as I know neither Xfce's appfinder nor the application or whisker menu support this. So it may be not as useful as it sounds to be.

So how smart should it be?

**Comment by newbieg** [comment]
For my own uses I actually think the simplest option would be best, I would go with option one. I wouldn't want actions outside of the search to influence the consistency of the applications that get higher priority. In gnome using the search to launch applications was faster for me than leaving the keyboard to use the mouse, so the quick launch in option 2 wouldn't affect me either way, but for most people I think that would be a nice option to have.

Sorry, that's not well written. I think that for your audience in general, option 2 would be the most worth-while option.

**Comment by gmc-holle** [comment]
Thanks for your advice. I guess you're right to handle only actions initiated by xfdashboard and to ignore everything outside the application. As you may guessed already I will go for option 2 and the first part is already implemented. I can now count, store and read in the number of launches of an application :)

Now the part calculating the relevance from these data is missing. Stay tuned :)

**Comment by gmc-holle** [comment]
Hi, it's done. You can now sort matching applications in a search by their relevance which is can be the weight of matching title, description or command or the number of times it was used or both.

To try it please try current git or wait till next development release 0.5.5. Regardless how long you wait you have to set an entry in xfconf, e.g. with the following command:

```
xfconf-query -c xfdashboard -p /components/applications-search-provider/match-mode -t uint -s 2
```

A value of 0 is the old default behaviour to sort them by title in alphabetical order. A value of 1 means to sort by weight of matching title, description or command (the more matches in these three areas the higher the score). A value of 2 means to sort them by how often they were used. You can combine the last two (weight and most-used) by setting a value of 3.

Feel free to re-open this issue if you encounter any problem.

**Comment by gmc-holle** [comment]
Sorry, there was a change in the namings at the last moment and also a bug was fixed that results were not shown if the results should be sorted by most-used only.

The property's name to manage the sorting has changed from 'match-mode' to 'sort-mode'. So the command above should be replaced with:

```
xfconf-query -c xfdashboard -p /components/applications-search-provider/sort-mode -t uint -s 2
```

**Comment by newbieg** [comment]
Thank you, it installed and the sort action is working great.
