### ISSUE TITLE
Not a issue just me being a noob :)

### ISSUE THREAD

**Issue by ryuuji89** [gmc-holle/xfdashboard#107]
1.How can I switch from list view to icon style view in app menu ?
2.Is there a way to show first the app menu instead of the active windows ?

Sorry for creating a issue  here but I did not knew where else to ask...

**Comment by gmc-holle** [comment]
No problem. I can mark this issue with label "question" ;)

According your questions:

1.) There is no option to switch between icon and list view in any view, e.g. applications menu. Only a theme can set this. If you want to change it and I assume you use the default theme "xfdashboard" then just copy the theme from /usr/share/themes/xfdashboard to ~/.themes/xfdashboard and replace in file `xfdashboard.css` the following

```
/* Applications view */
XfdashboardApplicationsView
{
        view-mode: list;
        spacing: 4.0;
}
```

with

```
/* Applications view */
XfdashboardApplicationsView
{
        view-mode: icon;
        spacing: 4.0;
}
```

I have to restart the application to get the changes applied.

2.) Yes, you can and at least two different ways. The easiest one is to start the xfdashboard settings application from Xfce's settings manager and to change the option "Switch to view when resumed" to "Applications view". This affects xfdashboard only if you run it at daemon mode.

When using xfdashboard in standalone mode then you can add the parameter `--view` on start-up. To switch to the applications menu on start-up, execute the following command:

```
xfdashboard --view applications
```

But be aware that 1.) works with nearly any version of xfdashboard but 2.) only at version 0.5.1 or higher.

If something doesn't work please feel free to ask or if you believe it's a bug then please file a new issue and describe your problem as precise as possible. :)

**Comment by ryuuji89** [comment]
Thanks a lot :).
