### ISSUE TITLE
Search result view mode icon crash

### ISSUE THREAD

**Issue by ryuuji89** [gmc-holle/xfdashboard#110]
When 
`/* Search view */
XfdashboardSearchView XfdashboardSearchResultContainer
{
	title-format: "<b><big>%s</big></b>";
	view-mode: icon;
	spacing: 4.0;
	padding: 4.0;
}
`
will crash xfdashboard when performing a search.

**Comment by gmc-holle** [comment]
This was seen when fixing issue #109 and was also fixed in latest commit cbb4b330b84abde03f5faca678e7f6cfe42c6e07 in git.

Thanks for the report.
