### ISSUE TITLE
Icon mode does not work with search view (in 0.5.5)

### ISSUE THREAD

**Issue by andy7d0** [gmc-holle/xfdashboard#111]
Enablig this mode produce segfault when someon tries to use search (typeing something)

**Comment by gmc-holle** [comment]
Sadly the icon mode is not as well tested as the list mode. So you may encounter more problems :(

But I could reproduce it and will try to solve it. Thanks for the report.

What is happening? The dynamic table layout manager which is used in icon mode takes the parent's size into account if available but the parent seems to ask the dynamic table layout manager to the size - it is a recursive loop :(

**Comment by gmc-holle** [comment]
I hope this issue is fixed with commit fb4b56dad0b305d4d5fb960c68a1b2dd52ff620e.

If possible please try again with latest git and re-open issue if this issue still exists.
