### ISSUE TITLE
Search broken

### ISSUE THREAD

**Issue by andy7d0** [gmc-holle/xfdashboard#112]
if we have a lot results (more than show instantly) and use function "show all N results" a new search with a new word will give us no results.
And, sometimets, many (but not all) labels in the result list are broken. But it may be unrelated.

**Comment by andy7d0** [comment]
And if i repeat "show 5 more..." many times (until no more results) search show the same behevior

**Comment by gmc-holle** [comment]
Thanks for the report but I cannot reproduce it. I think you start a new search in a way I haven't recognized yet.

So could you please try to describe each step you did as precise as possible? I'm interested only in the action to perform like where to click, when to hit which key etc.

Just one question before: When you started the new search were the first characters of the word to search the same as in the search before?

**Comment by andy7d0** [comment]
I use standalone Xfdash... (not daemonized).
Then I type just one char (i.e. 'a').
It gives me 84 possibilities (on my system).
Then I click 'show all ....' and scroll down (or, else, i cat click 'five more' many times, but not just one or two)
Then (here is your question) I clear search box (pressing backspace - it's just one char) and type new chars to search. And no item found.
Also, when I scroll long search list with mouse it's look crappy: somtimese some icons broken, some labes broken etc, but it  not always happends.

**Comment by gmc-holle** [comment]
Ok, I see. That's really a bug. The problem is that the view is getting smaller with the new search but it does not scroll to the beginning and offers no scrollbars.

That means that the search works and results are available and displayed but are moved out of sight :( Damn, I thought I had solved it with version 0.5.5

**Comment by andy7d0** [comment]
Yes, sometimes it's scrolled half item and no way to scroll up
15 Фев 2016 г. 12:44 пользователь "gmc-holle" <notifications@github.com>
написал:

**Comment by gmc-holle** [comment]
I hope I fixed it with lastest commit 426b12118af0faedbcaf9e3f773ba9e23d14a684 as it looks good to me.

If possible please check latest git and reopen issue.
