### ISSUE TITLE
budgie-panel appears in the list of applications

### ISSUE THREAD

**Issue by fossfreedom** [gmc-holle/xfdashboard#113]
Hi,

  I'm just experimenting to see if xfdashboard would be a good fit with the "budgie-desktop" (the new desktop from Solus Linux)

In the list of applications running it says "budgie-panel" is running.  Obviously this is one of the panel's that budgie displays.

Is there anyway to hide a particular application from being displayed in xfdashboard?

This may just be a bug in budgie-desktop - so how does xfdashboard determine the list of applications running to display on the left hand side?  Possibly budgie-desktop is "incorrectly" making their budgie-panel appear to be an application.

![](http://i.imgur.com/GktlNMd.png)

**Comment by gmc-holle** [comment]
Hi,

first of all: Thanks for trying xfdashboard :) and for the screenshot. I shows me that xfdashboard also recognizes other applications than the usual ones (firefox etc.) as running like bungie-panel. That's great to see for me.

But back to your question how xfdashboard determines if an application is running and if an icon should be displayed in quicklaunch. I'm lazy so I copy the commit message ;) I hope it explains it well enough.

```
The application tracker tries to determine and to keep track of running application. It does it by in two ways currently for each new window opened.
    
    1.) Parse the environment variables of the process ID which own the window. If it has the environment variables GIO_LAUNCHED_DESKTOP_FILE and GIO_LAUNCHED_DESKTOP_FILE_PID and GIO_LAUNCHED_DESKTOP_FILE_PID matches the process ID of the window's owner process then it assumed that the application in GIO_LAUNCHED_DESKTOP_FILE is running. This step only work at Linux currently.
    2.) Get some properties from the window (resource class etc.), add '.desktop' to the value and try to lookup a matching application in XfdashboardApplicationDatasbase, first with unmodified value and then in all lower-case.
```

Currently I do not support some kind of "blacklisting" but maybe it is a good idea. Could you copy the .desktop file for the bungie panel in this issue?

**Comment by fossfreedom** [comment]
Hi - the desktop file is here:

 - https://github.com/solus-project/budgie-desktop/blob/master/panel/budgie-panel.desktop.in.in

**Comment by fossfreedom** [comment]
As an aside - I was looking at a youtube video for xfdashboard (https://www.youtube.com/watch?v=EkmiR-cNoCM) and the right hand pane was only partially visible until you moved the mouse into that area.

Under budgie-desktop - this right hand pane was always fully visible - you'll note where my cursor is in the screen shot and the full workspace display on the right hand side.  Should I raise another issue?

**Comment by gmc-holle** [comment]
> Hi - the desktop file is here:
> https://github.com/solus-project/budgie-desktop/blob/master/panel/budgie-panel.desktop.in.in

Thanks for the desktop file. I thought I would find an entry that could be interpreted as a hint not to display it but there isn't any. But I haven't seen any desktop file with such a hint.

What I see by looking at the code of bungie-panel so far is that it sets the window type to "dock" but does not set the flags "skip-tasklist" and/or "skip-pager". My understanding is that without the flags this application should also be shown in the task list (e.g. by pressing ALT+TAB). If it also listed there then xfdashboard should also do. But maybe I'm wrong and windows of type "dock" shouldn't be shown at all. I'm really not sure if it is a bug or not :(

> As an aside - I was looking at a youtube video for xfdashboard (https://www.youtube.com/watch?v=EkmiR-cNoCM) and the right hand pane was only partially visible until you moved the mouse into that area.
> Under budgie-desktop - this right hand pane was always fully visible - you'll note where my cursor is in the screen shot and the full workspace display on the right hand side. Should I raise another issue?
That highly depends on the theme used. The default theme "xfdashboard" uses a collapse box for the workspace selector in its layout file while other theme do not.

You'll see the difference at https://github.com/gmc-holle/xfdashboard/blob/master/data/themes/xfdashboard/xfdashboard.xml#L93 (with auto-collape workspace) and https://github.com/gmc-holle/xfdashboard/blob/master/data/themes/xfdashboard-dark/xfdashboard.xml#L93 (always completely visible workspace).

If you more interested in theming I hope the documentation at http://xfdashboard.froevel.de/theming-unstable.html will help.

**Comment by fossfreedom** [comment]
Hi thanks for the feedback,

  as you can see I've posed the question on the Solus tracker ... my feeling is that windows with a dock hint should not be displayed - e.g. any panel based app like cairo-dock, AWN shouldnt be displayed.

Thanks for the links for the theme stuff.  I'll have a look - although I'm not really familiar how to change  themes.  

I'm using the arc-theme BTW - if you have any hints as to what needs to be changed please let me know.

thanks.

**Comment by ikeydoherty** [comment]
Hey. We'll fix this from Budgie, don't worry yourself trying to fix it here :)

**Comment by ikeydoherty** [comment]
We've fixed this in Budgie in git: https://github.com/solus-project/budgie-desktop/commit/0758ffd7aaf53f54b5b74462753a6f2a70182ccb

It will become part of the next point release

**Comment by gmc-holle** [comment]
I couldn't rest. Maybe it's a bug and I have to check it and .... ermmm ... yes well. It's a bug because I do not check at all if this window is "visible" when I try to find the running application for it unlike I did at the windows view where I check if this window is "visible" before adding it to the view.

So thank you for reporting :) I'll try to fix it with the next release candidate (0.5.91). I'll open a new issue #114 for it.

But anyway I'm very interested what the other think about the "skip-pager" and "skip-tasklist" flags.

Regards theming: Do you use any of the preinstalled themes that come with xfdashboard? If you do than any theme other than the default theme, e.g. xfdashboard-dark, xfdashboard-wine etc. will not have the collapsable workspace selector. If you want this feature but also the look'n'feel of the selected theme then you have to copy your favorite theme to ${HOME}/.themes and then edit the file `xfdashboard.xml`. Look for the following lines:

```
[...]

    <child>
        <object class="XfdashboardWorkspaceSelector" id="workspace-selector">
            <property name="can-focus">true</property>
            <property name="y-expand">true</property>
            <property name="show-current-monitor-only">true</property>
        </object>
    </child>

[...]
```

and replace them with

```
[...]

    <child>
        <object class="XfdashboardCollapseBox" id="workspace-selector-collapse-box">
            <property name="y-expand">true</property>

            <child>
                <object class="XfdashboardWorkspaceSelector" id="workspace-selector">
                    <property name="can-focus">true</property>
                    <property name="y-expand">true</property>
                    <property name="show-current-monitor-only">true</property>
                </object>
            </child>
        </object>
    </child>

[...]
```

You have either to restart xfdashboard or switch between the themes to get the changes applied.

**Comment by ikeydoherty** [comment]
@gmc-holle should be noted that the budgie-panel window sets `_NET_WM_WINDOW_TYPE_DOCK`, the linked commit simply enabled `_NET_WM_STATE_SKIP_PAGER` and `_NET_WM_STATE_SKIP_TASKBAR`

Whether it's correct to automatically skip all docks, I'm unsure, but in reality I'd be very surprised otherwise. Dock-type windows follow different focus patterns per the EWMH spec, and modern window managers/compositors enforce specific requirements and conditions on dock windows (undecorated by default, explicit focus-request system, skip window management, etc)

**Comment by gmc-holle** [comment]
@ikeydoherty thanks for the explaination. :)

**Comment by ikeydoherty** [comment]
@gmc-holle most welcome :) Keep up the awesome work with xfdashboard, it's looking seriously hot ^^

**Comment by fossfreedom** [comment]
@gmc-holle - I need to apply the xfconf-query statement as a default rather then letting the user manually set it themselves. (xfconf-query -c xfdashboard -p /theme -n -t string -s {theme-name})

Is there a global setting somewhere to always apply - let say - xfdashboard-dark 

I presume there isnt a gsetting value of somesort I can override- is there something I can patch myself to autoapply xfdashboard-dark?

**Comment by gmc-holle** [comment]
I'm not really a Xfconf expert even if I really like it and have wriiten a Xfconf backend for GSettings. But I think it is possible to provide default values different from the ones that may be hard-coded into the application like xfdashboard.

It is really untested but it looks like that you can create an XML file with only the values for the properties you want to preset and store this file system-wide. The usual place seems to be /etc/xdg/xfce4/xfce-perchannel-xml/ . At least I have three files from three application with default values that I've overwritten with my settings (XML files) in my user config directory ${HOME}/.config/xfce4/xfce-perchannel-xml/ .

So I would try to create a XML file at /etc/xdg/xfce4/xfce-perchannel-xml/xfdashboard.xml with following content and login a complete new user to test if this settings is preset and used:

```
<?xml version="1.0" encoding="UTF-8"?>

<channel name="xfdashboard" version="1.0">
  <property name="theme" type="string" value="xfdashboard-dark"/>
</channel>
```

If it works you could also preset the default favourites ;)

On the other hand ask the experts at Xfce (IRC, Mailing list etc.) ;)

**Comment by fossfreedom** [comment]
excellent - the patch works just fine.  Cheers!

when I set the theme to be xfdashboard the right hand panel for the workspaces correctly hide.

None of the other xfdashboard themes (e.g. xfdashboard-dark) hide like xfdashboard.  Why is the partial hiding limited to just the one theme?

**Comment by gmc-holle** [comment]
Only the default theme was done by me and all other themes are contributed.

**Comment by fossfreedom** [comment]
ok - cheers.
