### ISSUE TITLE
Application tracker does not check windows "visibility" before trying to determine running application

### ISSUE THREAD

**Issue by gmc-holle** [gmc-holle/xfdashboard#114]
The applicationt tracker handles each window opened regardless if it is a visible window before it tries to find the corresponding application for this window.

The "visibility" includes also minimized or hidden windows as these window exist and therefore an application is running. Therefore application tracker should only check if skip-tasklist or skip-pager is set to prevent looking up the running application.

This bugs is a result of discussion in issue #113

**Comment by gmc-holle** [comment]
@fossfreedom If possible and familar with git could you please try if this fixes your issue with xfdashboard and budgie panel. But budgie panel has to be fixed with the changes of solus-project/budgie-desktop#347

**Comment by fossfreedom** [comment]
@gmc-holle - thanks for your super speedy response :)  I'll grab these changes together with the budgie changes and test asap.

**Comment by gmc-holle** [comment]
Closing this issue due to response in #113
