### ISSUE TITLE
hot corner support when using budgie

### ISSUE THREAD

**Issue by fossfreedom** [gmc-holle/xfdashboard#122]
is there a xfquery or similar that I can use to get hotcorner support to invoke xfdashboard when running  budgie-desktop?

obviously the user can just run up xfdashboard-settings ... I'm just contemplating making the default of the hotcorner plugin to be switched on.  If you think I should manage this as a patch please can you advise what file in the source-code I need to tweak?

**Comment by gmc-holle** [comment]
Yes, there is ;)

```
xfconf-query -c xfdashboard -p /enabled-plugins -a -t string -s hot-corner
```

If you want to enable more plugins, e.g. Gnome-Shell search provider, just add additional "-t string -s <<ID OF PLUGIN>>" to the command above:

```
xfconf-query -c xfdashboard -p /enabled-plugins -a -t string -s hot-corner -t string -s gnome-shell-search-provider
```

**Comment by fossfreedom** [comment]
many thanks!

Is there a way to make a global change rather than at a per user level?

**Comment by gmc-holle** [comment]
As said before I'm not an expert for xfconf but it seems possible. As describe in issue #113 (https://github.com/gmc-holle/xfdashboard/issues/113#issuecomment-190834249) I think you can do it the following way -  at least I would try this way ;)

* Log in as user, call xfdashboard settings and configure xfdashboard the way you want it
* If you also want to provide your own set of default favourites then start xfdashboard and set up the favourites in the order you like
* If done log out
* Move `${HOME}/.config/xfce4/xfconf/xfce-perchannel-xml/xfdashboard.xml` to `/etc/xdg/xfce4/xfce-perchannel-xml/xfdashboard.xml` and set owner and group to *root* where `${HOME}` is the home directory of the user you used to set up xfdashboard.

Ensure that `${HOME}/.config/xfce4/xfconf/xfce-perchannel-xml/xfdashboard.xml` does not exist and log in as this user again. I believe the default value will now be unchanged and reflect the values set in `/etc/xdg/xfce4/xfce-perchannel-xml/xfdashboard.xml`. If it does it should do it you every other user also.

**Comment by fossfreedom** [comment]
actually that works very nicely!

Many thanks for this :+1:
