### ISSUE TITLE
--view command line flag doesn't seem to work?

### ISSUE THREAD

**Issue by sz3** [gmc-holle/xfdashboard#124]
I say "doesn't seem to", because the [settings documentation](http://xfdashboard.froevel.de/settings.html) claims:
> Valid names for built-in views are: __windows__ and __applications__.

So, I expect the `--view` command line option to accept the following:
`xfdashboard --view=applications`
or perhaps
`xfdashboard --view applications`

... and open directly to the applications view. It doesn't work for me on 0.5.92 -- it did way back on 0.5.2. I'm using the builds from xubuntu-dev/extras ubuntu ppa, for whatever that's worth.

Is this feature being abandoned? If not, it'd be cool if it was documented, since I'd like to use it. :)

**Comment by gmc-holle** [comment]
No, this command-line option is not obsolete and should still working. But the view IDs have changed. So could you try the following argument?

`xfdashboard --view=builtin.applications`

Does this work?

**Comment by gmc-holle** [comment]
It was a simple bug :( ... but it is now fixed :)

It should work with commit 683f5048c1dc37af503709e3c8666efce77f6ba5.

Please notice that the internal view names must be specified as shown in the comment before. I will update the docs before releasing the next stable version 0.6.0.

When using the developments versions please refer to the development docs at http://xfdashboard.froevel.de/settings-unstable.html and http://xfdashboard.froevel.de/theming-unstable.html.

And thanks for reporting the bug.

**Comment by sz3** [comment]
Excellent. Thanks!
