### ISSUE TITLE
(Idea)Expose and apps view

### ISSUE THREAD

**Issue by divinae** [gmc-holle/xfdashboard#126]
1) May you give opportunity to theme xfdashboard like expose/scale/skippy-xd? I mean, i could delete favorites and view changer, but still can't show windows from all workspaces.

2) Application view should be more like gnome view. Icons in 2D works better in my opinion.

**Comment by gmc-holle** [comment]
Hi,

1.) Yes, it would be possible to add a themable property like "filter-workspace-windows" to show only the windows of current workspace in the windows view or to show all windows of all workspaces. But these windows will have the same limitation as minimized windows. That means the window content will not be shown or remain unchanged if the window is not at the current workspace. Running xfdashboard in daemon mode is recommended for better UI experience. (to have a still image of the windows at least). I Think I will add this feature in the upcoming developement release cycle.

2.) Hmmm .... I don't understand. Could you try to explain it to me more precisely? The icons are 2D - at least from a programming point of view and the application view uses the icons passed by the system (via Garcon and/or Glib). So I have no clue what you are referring to.

**Comment by divinae** [comment]
![Image of Gnome](https://upload.wikimedia.org/wikipedia/commons/0/0e/Gnome_Shell_Applications_Screen.png)

i mean icons should be like table[][] with x and y position on screen

**Comment by gmc-holle** [comment]
ah ... ok, I see. This is already possible but depends highly on the theme you use because the theme tells xfdashboard how to show the application menu.

See property "view-mode" at http://xfdashboard.froevel.de/theming.html#theme-stylable-properties-XfdashboardApplicationsView

**Comment by gmc-holle** [comment]
According 1.) It's done with commit 6b11d475af8f868d0c85fc9e1338be4627931e2a. You can now show all windows of all workspaces and of all monitors in one window view. Just set the property 'filter-workspace-windows' to true for XfdashboardWindowsView in the CSS file of your theme. And you need latest git version of course (or wait for version 0.7.1 getting released)

According 2.) As said before it is already posible but depends on the theme.

Marking this issue as solved.

**Comment by divinae** [comment]
i cant make it work :/

**Comment by gmc-holle** [comment]
Sorry for the delay but I'm quite busy at the moment ... sadly not for xfdashboard.

First of all you need the latest code from git as version 0.7.1 is still not yet release. There too little changes to make a new development release. So you have to clone this git repository and compile and install xfdashboard on your own.

Next you should copy a theme which you use as base for your changes. That's much easier than to create a theme from scratch. If you want to use xfdashboard's default theme, then copy the folder `xfdashboard` from /usr/share/themes/ to $HOME/.themes or $HOME/.local/share/themes and rename the theme's folder name as you wishes. Modify the CSS file `xfdashboard.css` by looking up the following text lines and add the missing lines or replace the changed ones:

```
/* Applications view */
XfdashboardApplicationsView
{
        view-mode: icon;
        spacing: 4.0;
}
...
/* Windows view */
XfdashboardWindowsView
{
        spacing: 8.0;
        prevent-upscaling: true;
        view-icon: windows-view.png;
        filter-monitor-windows: true;
        filter-workspace-windows: false;
}
```

If you changed the folder's name for the theme as suggested, your new theme should be listed in xfdashboard's settings and then select it.

If you make further changes to your theme after you selected it in the settings, then you have to select any other theme and switch back to your new one to apply the changes.

I hope I could help.

**Comment by gmc-holle** [comment]
Ahh ... don't forget to modify the file `xfdashboard.theme` in your theme's folder if you renamed it to reflect this change.

**Comment by divinae** [comment]
Thanks, it actually work, but there is something more work to make it useful.I mean, when I select app from other workspace i should be move to this workspace.

**Comment by gmc-holle** [comment]
Absolutely. You are right. It should switch to the workspace before activating the window.

It's done with commit 653b38b95f7281691f42f8c9fb6e9171e9e50db5

**Comment by divinae** [comment]
It's nice :)
