### ISSUE TITLE
(idea)Quick close

### ISSUE THREAD

**Issue by divinae** [gmc-holle/xfdashboard#128]
Could you implement something like - https://extensions.gnome.org/extension/352/middle-click-to-close-in-overview/ ?

**Comment by gmc-holle** [comment]
What is the advantage of this to clicking the close button? On the other hand maybe someone could create a plugin for xfdashboard to implement such a functionality as at the moment I don't think it belongs into the core.

**Comment by divinae** [comment]
Of course it should be a plugin.
It's faster to click middle mouse button vs. find small close button in corner

**Comment by gmc-holle** [comment]
Plugin added to current git. Have fun :)
