### ISSUE TITLE
libxfdashboard.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Pablohn26** [gmc-holle/xfdashboard#133]
Hi,

using Debian 9 and XFCE, I do autogen.sh, make and make install and once I am going to open  xfdashboard I get
>xfdashboard-settings 
>xfdashboard-settings: error while loading shared libraries: libxfdashboard.so.0: cannot open shared object file: No such file or directory

**Comment by Pablohn26** [comment]
I have fixed it with 
> sudo ln -s /usr/local/lib/libxfdashboard.so.0 /usr/lib/libxfdashboard.so.0

seems some compiling instructions are wrong. I have done all by default.

**Comment by gmc-holle** [comment]
Hi,

does it only affect the binary "xfdashboard-settings"? Or does it affect the binary "xfdashboard" (the main application) also?

**Comment by Pablohn26** [comment]
Hi @gmc-holle,

xfdashboard was affected too.

**Comment by gmc-holle** [comment]
Hmmm ... I do not really know how to use and write Makefiles but I think I have to add -Wl,-rpath=$(prefix)/lib somehow. I will try it but I need some time to test it.

**Comment by gmc-holle** [comment]
I looked at this issue and one solution could be to add "-rpath $(libdir)" to Makefile.am files at xfdashboard and xfdashboard-settings. But I also read to avoid setting "-rpath" so at the moment I cannot decide how to handle this issue.

You also install into /usr/local/lib which should in your library search path by default - see /etc/ld.so.conf or /etc/ld.so.conf.d/*.conf. Maybe you just need to run ldconfig after installing xfdashboard to /usr/local? Could you try to remove the symlink and run ldconfig and check if xfdashboard can be started?

**Comment by Pablohn26** [comment]
I have installed debian from docker, installed all requirements and the error is still reproducible.

Then I have run ldconfig and the error changes to 

>Unable to init server: Could not connect: Connection refused

which is clear due to lack of X on docker, so seems running ldconfig fix the problem :)

**Comment by gmc-holle** [comment]
Thanks for your feedback. So I do not change anything at the code and close this issue

**Comment by DanieleDaccurso** [comment]
Hello

I had exactly the same issue on Debian Stretch and had to do exactly the same fix. Debian with X, no Docker.
