### ISSUE TITLE
Option to avoid multi-monitors extending 

### ISSUE THREAD

**Issue by bflorat** [gmc-holle/xfdashboard#136]
Is is possible to get an option to avoid multi-monitors extending introduced in #14 ? 

I'd greatly prefer to see all monitors windows grouped on the primary display or on every monitor (like in Gnome Shell if I'm not wrong). 
Successfully tested workaround : in /usr/share/themes/xfdashboard/xfdashboard-1.0/xfdashboard.css (or in the others themes xfdashboard.css files) , change `filter-monitor-windows: true;` to `filter-monitor-windows: false;`

Thanks for this cool piece of software.

**Comment by gmc-holle** [comment]
Hi bflorat,

Hmmm ... I'm not really sure if I got it what you want. What do you mean by "avoid multi-monitors extending"? If changing the CSS file of your favourite theme (or of a newly created one) was successful, why isn't it the solution? What do you expend to be possible?

Thanks for using xfdashboard :D

**Comment by bflorat** [comment]
Hi, thanks to reply. 

I mean that I would like, instead of changing the css, to have an option to switch between the current behavior (ie, if you have 2 screens, you see thumbs of each screen on screen itself) and a behavior where all thumbs are displayed together on each screen. I find it a lot easier to find an app inside a single screen than searching on both screens.

BTW, I wrote a small howto about xfdashboard integration : http://florat.net/blog_tech/dashboard_under_xfce_real_howto

**Comment by gmc-holle** [comment]
I understand. But changing the theme is not an option? If not, would it be an option if I could an existing theme could be customized more easily because nowadays you have to copy the theme completely to ~/.themes/`(name of theme)` and then modify the files to match your needs.

**Comment by bflorat** [comment]
Yes, I guess it would be enough to create a special theme with all apps in each screen so it could be an example for changing the existing themes. You may also just document the line to change.
Cheers

**Comment by gmc-holle** [comment]
Hmmm ... do you have a suggestion what and where to document? I thought the documenation for theming and the available CSS options were ok ;)

Otherwise I would like to close this issue.

**Comment by gmc-holle** [comment]
I think it's ok as it is ... closing issue

**Comment by gsantner** [comment]
![screenshot_20180821-120349](https://user-images.githubusercontent.com/6735650/44395475-48087480-a53a-11e8-8482-70fcff34bb11.png)


@gmc-holle  I'm always getting search results on wrong (not primary) monitor. how can I turn this off? Have set value as below, but somehow it doesn't do anything at all
```
/home/user/.config/xfdashboard/themes/global.css
XfdashboardWindowsView {
        filter-monitor-windows: false;
}
```
I want to have everything shown on my primary monitor. (or advanced, where mouse currently is).
Any idea how to?
