### ISSUE TITLE
CLI option to toggle dashboard visibility

### ISSUE THREAD

**Issue by bflorat** [gmc-holle/xfdashboard#137]
I'd like a CLI option like xfdashbord -v or --visible that would just show the dashboard if it's not visible and hide it if it's visible. 

Why ? To call this switch when moving the mouse to a hotcorner and reproduce the gnome-shell behavior of hidding the dashboard when moving the mouse to the corner a second time (more convenient than ESC when you just want to close the dashboard without selecting an app).

Thanks, KUTGW

**Comment by gmc-holle** [comment]
Hi,

this option already exists and is short `-t` or long `--toggle`

```
~ $ xfdashboard --help
Usage:
  xfdashboard [OPTION...] - A Gnome Shell like dashboard for Xfce4

[...]
  -t, --toggle                           Toggles suspend/resume state if running instance was started in daemon mode otherwise it quits running non-daemon instance
[...]
```

Regards

**Comment by bflorat** [comment]
Fine, sorry about that, I saw this option but I didn't understand its goal when reading the command line doc [1]. I thought that resuming/suspending state was related to the the daemon mode. I would say instead : "Toggles visibility of the dashboard if running instance was started in daemon mode otherwise it quits running non-daemon instance"

Cheers

[1] "Toggles suspend/resume state if running instance was started in daemon mode otherwise it quits running non-daemon instance"
