### ISSUE TITLE
alt+tab behaviour?

### ISSUE THREAD

**Issue by rickmed** [gmc-holle/xfdashboard#138]
Switch through previews with alt+tab?

thank you for this awesome app.

**Comment by gmc-holle** [comment]
Thanks :)

But what do you ask? xfdashboard does not handle alt+tab so I don't know what you are referring to.

**Comment by rickmed** [comment]
Would be cool if it could handle it. Meaing, if I press alt+tab it would show xfdashboard and continue switching windows if pressing tab while continuously pressing alt.

**Comment by gmc-holle** [comment]
That's beyond what xfdashboard should do and can do. Alt+TAB is usually handled by the window manager, e.g. xfwm4, and I think that the best. If using xfwm4 as window manager (the default one at Xfce) than it has got a really nice window preview when pressing Alt+TAB. I wouldn't change it ;)I just don't know currently at which version of xfwm4 it was introduced

**Comment by rickmed** [comment]
I do think xdashboard would be better as a potential (choice!) replacement for xfwm switcher. What about this? " Also, would be amazing if while pressing alt (or whichever key binding), xfdashboard would assign (and show) a number to each window so one could press that number and switch immediately to it."

**Comment by gmc-holle** [comment]
xfdashboard is not designed to provide a window switcher via Alt+TAB and it is hardly possible. I even could not imagine how it should look and behave. It could not do it equal or better than xfwm. xfwm does its job great ;)

Showing numbers at the windows and selecting them by pressing the number is already possible and enabled by default. The only limitation by the default key binding file is that you have to move the focus to the windows (by pressing TAB) before you can press the left CTRL key. As long as CTRL is pressed, numbers will be shown instead "X" for closing a window. If you keep CTRL pressed and press the number the associated window will be selected and activated.
