### ISSUE TITLE
Instead of windows on the xfdashboard screen, vertically flattened stripes are like windows

### ISSUE THREAD

**Issue by sujaataarya** [gmc-holle/xfdashboard#141]
Hello!
Xfdashboard - Such a wonderful program!
But a several unpleasant bugs were noticed in the version:
https://github.com/gmc-holle/xfdashboard/archive/0.7.1.tar.gz
1) Instead of windows on the xfdashboard screen, vertically flattened stripes are like windows;
2) Hotcorner does not always work.
I made a rollback back:
https://github.com/gmc-holle/xfdashboard/archive/0.6.1.tar.gz
As a result, it works remarkably and error-free, and I'm happy with everything.
Is it possible to solve problems in the new version of xfdashboard?
Best regards, Sergey.

**Comment by gmc-holle** [comment]
Oh, that's sad to hear that the new version isn't working well at your system .... but that's what development version like 0.7.1 are for ;)

But I need more information to understand what is going wrong. What do you mean by "[...] vertically flattened stripes are like windows"? Maybe a screenshot could help to see the problem?

Do you use the "hotcorner" plugin provided by xfdashboard? Were you running xfdashboard in daemon mode when you upgraded to 0.7.1?

Last but not least I need some information about your system at all. What distribution are you using? As you refer to the tagged source codes in GitHub I think you are compiling and installing xfdashboard from the sources. Could you provide the summary at the end of the output of the configure script? It should look like this:

```
# ./configure
[...]
Build configuration:
  Package:          xfdashboard
  Version:          0.7.1git.UNKNOWN
  Revision:         
  Library version:  700:1:700

Library versions used:
  libwnck:          3.20.1
  clutter:          1.26.0
  cogl:             1.26.0
  gtk+:             3.20.9
  glib:             2.48.2
  gio:              2.48.2
  gio-unix:         2.48.2
  garcon:           0.5.0
  libxconf:         4.12.1
  libxfce4ui:       4.13.1
  libxfce4util:     4.12.1
  dbus-glib:        0.102

Tools used:
  glib-genmarshal:  glib-genmarshal
  glib-mkenums:     glib-mkenums

Features enabled:
  XComposite:       yes
  XDamage:          yes
  Xinerama:         yes
```

Last but least: What GPU do you use? What drivers (Mesa, proprietary) and what version of this drivers?

Thanks your report and using xfdashboard :D

**Comment by sujaataarya** [comment]
Hello!  Where can I send screenshots?

**Comment by gmc-holle** [comment]
You can upload your screenshots right here in this issue when replying. An alternative is using in image upload service like imgur or "how-they-named".

**Comment by gmc-holle** [comment]
But besides the screenshot the other information are more important!

**Comment by pedherall** [comment]
This happens to me in xubuntu 16.04 and in manjaro 17. The GPU is Intel Haswell-ULT Integrated Graphics Controller with Mesa 17.0.1.

http://imgur.com/VyLPPHAl.png

[url=http://i.imgur.com/VyLPPHA.png]
  [img]http://imgur.com/VyLPPHAl.png[/img]
[/url]

**Comment by nonamedotc** [comment]
I am also seeing this on Fedora 25 with nouveau driver.

Here is an interesting observation - windows are rendered properly if we change the workspace and revisit the relevant workspace.

**Comment by gmc-holle** [comment]
I think I know where to look at. But can everyone suffering from this issue test if changed workspace forth and back will help restoring the "broken" windows?

**Comment by sujaataarya** [comment]
![_2017-03-21_12-29-13](https://cloud.githubusercontent.com/assets/12985719/24136782/3f8e7bd8-0e32-11e7-8952-755518331efe.png)

**Comment by sujaataarya** [comment]
If you close all windows, and then open the application again, then everything works fine.
![_2017-03-21_12-37-47](https://cloud.githubusercontent.com/assets/12985719/24136935/477e3a4e-0e33-11e7-8852-40e18640e4b0.png)

**Comment by sujaataarya** [comment]
However, simply changing the workspace does not restore the image of the windows in the program display.

**Comment by gmc-holle** [comment]
@sujaataarya As I see you have only one workspace then the workaround I asked for does not work for you. But closing windows and re-open them (or restarting the application) will work while xfdashboard is running in daemon mode? Did I understand right?

Then it looks like that xfdashboard does not get the signal that the windows have changed their size :(

**Comment by gmc-holle** [comment]
Ok, my question about the workaround with the workspaces was just in time with your answer ;)

**Comment by sujaataarya** [comment]
I have four workspace.  Just the windows were in one.
Now I will try to change the sizes of windows in different workplaces..

**Comment by sujaataarya** [comment]
I did various manipulations with the windows, and this time everything is fine...
![_2017-03-21_12-46-14](https://cloud.githubusercontent.com/assets/12985719/24137186/7eb7628c-0e34-11e7-815b-77bbeb810410.png)

**Comment by sujaataarya** [comment]
I apologize for the delay in replying.
I switched to version 0.6.1 and could not write about 0.7.1
Now I'm on version 0.7.1

I install through the package of AUR:
https://aur.archlinux.org/cgit/aur.git/snapshot/xfdashboard.tar.gz
Maybe this will help...

**Comment by gmc-holle** [comment]
Sorry, now I'm confused. The issue only happens on 0.7.0 or 0.7.1, right? Version 0.6.1 was working well all the time, wasn't it?

**Comment by sujaataarya** [comment]
Version 0.6.1 works well!
Version 0.7.0 I did not install, but I can try to put it if there is a link to the download.
Then I installed 0.7.1 and there are misunderstandings with the display.

**Comment by sujaataarya** [comment]
OK.  )) I found, I will now building.
https://github.com/gmc-holle/xfdashboard/archive/0.7.0.tar.gz

**Comment by gmc-holle** [comment]
Could you send me the output of the configure script? It look similar to this:

```
# ./configure
[...]
Build configuration:
  Package:          xfdashboard
  Version:          0.7.1git.UNKNOWN
  Revision:         
  Library version:  700:1:700

Library versions used:
  libwnck:          3.20.1
  clutter:          1.26.0
  cogl:             1.26.0
  gtk+:             3.20.9
  glib:             2.48.2
  gio:              2.48.2
  gio-unix:         2.48.2
  garcon:           0.5.0
  libxconf:         4.12.1
  libxfce4ui:       4.13.1
  libxfce4util:     4.12.1
  dbus-glib:        0.102

Tools used:
  glib-genmarshal:  glib-genmarshal
  glib-mkenums:     glib-mkenums

Features enabled:
  XComposite:       yes
  XDamage:          yes
  Xinerama:         yes
```

**Comment by sujaataarya** [comment]
Build configuration:
  Package:          xfdashboard
  Version:          0.7.1
  Revision:         
  Library version:  700:1:700

Library versions used:
  libwnck:          3.20.1
  clutter:          1.26.1
  cogl:             1.26.1
  gtk+:             3.22.10
  glib:             2.50.3
  gio:              2.50.3
  gio-unix:         2.50.3
  garcon:           0.4.0
  libxconf:         4.12.1
  libxfce4ui:       4.12.1
  libxfce4util:     4.12.1
  dbus-glib:        0.108

Tools used:
  glib-genmarshal:  glib-genmarshal
  glib-mkenums:     glib-mkenums

Features enabled:
  XComposite:       yes
  XDamage:          yes
  Xinerama:         yes

**Comment by sujaataarya** [comment]
I will now build garcon: 0.5.0

**Comment by gmc-holle** [comment]
garcon should not change anything about this issue because it handles only the applications and menus.

But I see you have clutter version 1.26.1 installed but I don't know that this version is released (and I do not find the sources at GNOME's FTP service for download). So I cannot test it and such a different version of Clutter could change little things :(

**Comment by gmc-holle** [comment]
Ah, I see. You have a git snapshot of latest clutter developement installed.

**Comment by sujaataarya** [comment]
do not know why the conclusion was 1.26.1
In the package manager, this version information
clutter  1.26.0+24+g79da526-1

![_2017-03-21_14-47-02](https://cloud.githubusercontent.com/assets/12985719/24141510/75fcc694-0e45-11e7-857d-b755925212b4.png)

**Comment by sujaataarya** [comment]
![_2017-03-21_14-50-34](https://cloud.githubusercontent.com/assets/12985719/24141609/cc562904-0e45-11e7-8279-dc11d2ee271e.png)

**Comment by sujaataarya** [comment]
[xfdashboard-makepkg.txt](https://github.com/gmc-holle/xfdashboard/files/857764/xfdashboard-makepkg.txt)

**Comment by gmc-holle** [comment]
I commited new experimental code to get the sizes of the windows to display. I hope this will fix your issue. Do you mind to test the latest Git version? The commit 6071b997e6ce4d8053c30a9489000e12abb9f76c contains the new code and will produce warnings while compiling. If it works I will clean up the new code.

**Comment by sujaataarya** [comment]
I rebuilt with the replacement of the file live-window-simple.c and installed xfdashboard-0.7.1
So far, everything works well!

**Comment by sujaataarya** [comment]
[xfdashboard-makepkg-new.txt](https://github.com/gmc-holle/xfdashboard/files/864100/xfdashboard-makepkg-new.txt)

**Comment by sujaataarya** [comment]
![_2017-03-23_13-57-45](https://cloud.githubusercontent.com/assets/12985719/24239696/c6076f5e-0fd0-11e7-99af-efeea01e555a.png)

**Comment by gmc-holle** [comment]
Really? It works now for you? :) :) :) Do you consider the issue as solved with this patch?

**Comment by gmc-holle** [comment]
Ah ... a screenshot :D Cool, then I will clean up the code and it will go into next version 0.7.2

**Comment by sujaataarya** [comment]
Thanks, everything works well, I'll observe, and if there are errors I will inform you.
Thank you for your support and improvement!
Best regards, Sergey!

**Comment by gmc-holle** [comment]
New experimental code replaces now the old code to determine size of XfdashboardLiveWindowSimple.

Closing this issue

**Comment by gmc-holle** [comment]
@sujaataarya Thanks for reporting and testing :)

**Comment by sujaataarya** [comment]
Hello!
Though the topic is closed.  All the same I want to ask.
Because of what the artifacts on the image in the presented screenshot can penetrate?
![_2017-03-24_14-06-49](https://cloud.githubusercontent.com/assets/12985719/24287439/8c80a608-109b-11e7-9335-a6bd0e2a9366.png)

**Comment by gmc-holle** [comment]
I have seen this distortion also. Especially when using the xfce terminal application (although I think it happens with all terminal application based on libvte). Is it a minimized window while running xfdashboard in daemon mode?

It seems that Cogl (used by Clutter) cannot get an image when the window is minimized (unmapped at X server) and fetches garbage. As xfdashboard uses the latest image from Cogl via Clutter it also fetches this garbage. I don't have any solution for this kind of problem :/
