### ISSUE TITLE
newly installed packages do not show up in xfdashboard search

### ISSUE THREAD

**Issue by nonamedotc** [gmc-holle/xfdashboard#142]
I run xfdashboard as a daemon at start up. If I install a new graphical application, it shows up on Xfce menu once the package is installed. 

However, the same package does not show up in xfdashboard search results or menu. If I quit, using

```xfdashboard -q ```

and restart it in daemon mode using

```xfdashboard -d```

I can see the newly installed application. Can this be looked at?

```
$ rpm -qa xfdashboard
xfdashboard-0.7.1-1.fc25.x86_64

$ cat /etc/redhat-release 
Fedora release 25 (Twenty Five)
```

Thanks.

**Comment by gmc-holle** [comment]
Strange, exactly this behaviour was tested before it was committed back in the earlier versions. So what has changed? Did this issue also affect version 0.7.0 or the latest stable version of the 0.6 series?

**Comment by gmc-holle** [comment]
Just one quick question: Do I assume right that you find the newly installed application neither in the application menu which you can browse nor in the search results?

**Comment by nonamedotc** [comment]
I can reproduce this in 0.7.0 for sure. Do you want me to test in 0.6.x? I am pretty sure I did not see this before.

And, yes. I can neither find the application in browsable menu nor in the search results. The only place I can find it is in Xfce menu.

**Comment by gmc-holle** [comment]
Yes, it would be great if you could test it also again 0.6 although I expect the same result but only if this version is linked against the same library versions of Clultter, gtk+, glib etc.

**Comment by gmc-holle** [comment]
I've implemented the new debugging code and committed it to git (commit 94f19189ddec10e6fe73b7bf6cbc40a6a7cbc5fa). It should help filtering the debug messages for the "apps" relevant ones. Could you checkout latest git, compile and run it? To get the debug messages the environment variable XFDASHBOARD_DEBUG must be set to "apps", e.g.for daemon mode:

```
XFDASHBOARD_DEBUG=apps xfdashboard --daemonize
```

Then just install and uninstall an application installing a desktop file. Or vice versa if the application is already installed ;)

Could you please paste the debug message here and tell me which application (desktop file and path location of this file) was installed and uninstalled? Could you also paste the summary of the configure script containing the library version etc.?

**Comment by nonamedotc** [comment]
Library versions - 

```
Library versions used:
  libwnck:          3.20.1
  clutter:          1.26.0
  cogl:             1.26.0
  gtk+:             3.22.9
  glib:             2.51.4
  gio:              2.51.4
  gio-unix:         2.51.4
  garcon:           0.5.0
  libxconf:         4.12.1
  libxfce4ui:       4.12.1
  libxfce4util:     4.12.1
  dbus-glib:        0.108

Tools used:
  glib-genmarshal:  glib-genmarshal
  glib-mkenums:     glib-mkenums

Features enabled:
  XComposite:       yes
  XDamage:          yes
  Xinerama:         yes
```


[xfdashboard_debug.txt](https://github.com/gmc-holle/xfdashboard/files/866556/xfdashboard_debug.txt)

**Comment by gmc-holle** [comment]
Thanks for the debug log. I see that you have installed the "mousepad" text editor. The application database recognized this newly installed application and added it to database. The application menu model which is used when browsing through the application menus also reloaded and should show mousepad.

But I also see that the signal emission for applications being added or removed at the application database did not work because I used the wrong marshalling function. That affects the application search provider which is used when you use the search in xfdashboard. This one did not reload so searching for mousepad will not show anything. I corrected the signal emission definition in commit 056ec94f0987e00213648078b7200f7efbef2094

Could you checkout latest git and try again?

**Comment by gmc-holle** [comment]
I installed Fedora 25 in a VM and compiled xfdashboard from the latest git. Then I installed and remove the app "mousepad" several times and xfdashboard was able to find it if installed or did not if removed. So it works as expected.

Can you confirm?

**Comment by nonamedotc** [comment]
Sorry for the delay. I was away.

I can confirm building from the latest git works as expected. search and menu both work without having to quit daemon mode and restarting xfdashboard.

Thanks for the quick fix. I will close the issue!

**Comment by gmc-holle** [comment]
No problem. Thanks for all :)
