### ISSUE TITLE
xfdashboard segfaults if recursion in theme css

### ISSUE THREAD

**Issue by gwhitney** [gmc-holle/xfdashboard#143]
If you include the following (obviously this happened by accident) in the theme.css file of a theme:

    @constants
    {
        wan: @alpha(@wan, 0.38);
    }

and then try to reference @wan anywhere in the remainder of the theme.css file, xfdashboard will segmentation fault on startup.

Analysis: Because of the @-constant reference recursion, theme-css.c is getting stuck in an infinite nest of recursive calls to _xfdashboard_theme_css_resolve_at_identifier_by_string(), and eventually the stack blows up, causing the segfault. Presumably you want to avoid the segfault; I attach a simple patch which should do that. (A useful error message indicating the identifier involved and the possibility there is a recursive definition might be even better.) One caveat: I have not tested this patch, because I am still too new to openSuse to understand how I take one package, obtain its source, uninstall the package from the repository, and then install my recompiled version of the package in its place, in a fashion in which it is easy to return to the repository's version of the package. Perhaps I need to learn to use OBS? In any case, this particular point was too minor to make it worthwhile to figure all that out, so I am offering the patch untested. It is quite straightforward as it stands, so it should work to avoid the segfault, but likely you will want to enhance it a bit to provide a better diagnostic.

[theme-css.c.patch.txt](https://github.com/gmc-holle/xfdashboard/files/910916/theme-css.c.patch.txt)

**Comment by gmc-holle** [comment]
Thanks for reporting this bug. I have to be honest that I didn't see that a recursion is possible and did not handle this case. Your analysis is absolutely right at my point of view. This recursion blows up the stack and causes a segfault.

I applied your patch but modified it a little bit to match may coding style ;) And it works well although it is not the final solution I wish to implement which should tell the user/designer which identifier causes the recursion. But it is much much better than a segfault :)

Thanks!

PS: I do not close this issue to remember me of my wish for the final solution.

**Comment by gmc-holle** [comment]
I added a recursion detection when resolving an @-constant identifier. In your example the output would be like this:

```
../xfdashboard/data/themes/xfdashboard/xfdashboard.css:20: failure around character ';' - Cannot resolve identifier '@wan' because of indefinite recursion
../xfdashboard/data/themes/xfdashboard/xfdashboard.css:20: error: unexpected character ';', expected end of file - Parser did not reach end of stream
```

I think I can now close this issue finally :)
