### ISSUE TITLE
A few additional useful defaults/actions for focus and selection

### ISSUE THREAD

**Issue by gwhitney** [gmc-holle/xfdashboard#144]
A modest wish list:
1) The ability to specifiy what focusable actor is focused on startup/resume (currently startup is hard-wired to the search bar AFAICT, but personally I would like it to be on quicklaunch, and the options are for resume to do nothing, or activate the windows or applications view, but personally although "do nothing" is pretty OK my ideal would be to always have quicklaunch focused on resume.)

2) Additional actions that could be bound in Bindings.xml:
    selection-move-next (an action that would cycle through all selectable items in the actor, regardless of geometry)
    selection-move-previous (the same but in the reverse order)
    focus-move-first (like focus-move-next/focus-move-previous, but always goes to the first focusable actor in the list)
    focus-move-last (ditto but to last)

3) One more action but I am not quite sure how it fits in the current framework:
    focus-move-to (the idea is to be able to specify a key that always moves directly to a given actor. However, I am not sure in the current XML syntax how the destination actor would be specified, since
the source has to specify where the keystroke is accepted from and the target would have to be the focus manager.)

Thanks for wonderful software! Glen

**Comment by gwhitney** [comment]
BTW if you are interested in the background to these requests, you can see that (and some other ideas) at https://forum.xfce.org/viewtopic.php?id=11543.

**Comment by gmc-holle** [comment]
Hi. Thanks for your request and for using xfdashboard :)

1.) That's funny. I had this feature on my own wishlist since the day I implemented the possible to define which actors are focusable and in which order. But it needed your request to implement this. So I added a boolean attribute ```selected``` to <focus>  which should only the used once among all interface specified in all layout xml files ... and set to ```true```. It was implemented with commit 20920e77061d71ea82dd2ccea03c71b8e4a9f784 and will be available with next unstable release 0.7.2. I think I will release it soon as it has some major improvements.

2.) That should already be possible. All signal actions declared should be usable in bindings.xml. A simple grep over libxfdashboard/*.c should show you which object provides which action, e.g. XfdashboardFocusable provides "selection-move-next" and "selection-move-previous".

```
$ grep -B2 G_SIGNAL_ACTION libxfdashboard/*.c
libxfdashboard/application.c-		g_signal_new("exit",
libxfdashboard/application.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/application.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/focusable.c-			g_signal_new("selection-move-left",
libxfdashboard/focusable.c-							XFDASHBOARD_TYPE_FOCUSABLE,
libxfdashboard/focusable.c:							G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/focusable.c-			g_signal_new("selection-move-right",
libxfdashboard/focusable.c-							XFDASHBOARD_TYPE_FOCUSABLE,
libxfdashboard/focusable.c:							G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/focusable.c-			g_signal_new("selection-move-up",
libxfdashboard/focusable.c-							XFDASHBOARD_TYPE_FOCUSABLE,
libxfdashboard/focusable.c:							G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/focusable.c-			g_signal_new("selection-move-down",
libxfdashboard/focusable.c-							XFDASHBOARD_TYPE_FOCUSABLE,
libxfdashboard/focusable.c:							G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/focusable.c-			g_signal_new("selection-move-first",
libxfdashboard/focusable.c-							XFDASHBOARD_TYPE_FOCUSABLE,
libxfdashboard/focusable.c:							G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/focusable.c-			g_signal_new("selection-move-last",
libxfdashboard/focusable.c-							XFDASHBOARD_TYPE_FOCUSABLE,
libxfdashboard/focusable.c:							G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/focusable.c-			g_signal_new("selection-move-page-left",
libxfdashboard/focusable.c-							XFDASHBOARD_TYPE_FOCUSABLE,
libxfdashboard/focusable.c:							G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/focusable.c-			g_signal_new("selection-move-page-right",
libxfdashboard/focusable.c-							XFDASHBOARD_TYPE_FOCUSABLE,
libxfdashboard/focusable.c:							G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/focusable.c-			g_signal_new("selection-move-page-up",
libxfdashboard/focusable.c-							XFDASHBOARD_TYPE_FOCUSABLE,
libxfdashboard/focusable.c:							G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/focusable.c-			g_signal_new("selection-move-page-down",
libxfdashboard/focusable.c-							XFDASHBOARD_TYPE_FOCUSABLE,
libxfdashboard/focusable.c:							G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/focusable.c-			g_signal_new("selection-activate",
libxfdashboard/focusable.c-							XFDASHBOARD_TYPE_FOCUSABLE,
libxfdashboard/focusable.c:							G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/focus-manager.c-		g_signal_new("focus-move-next",
libxfdashboard/focus-manager.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/focus-manager.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/focus-manager.c-		g_signal_new("focus-move-previous",
libxfdashboard/focus-manager.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/focus-manager.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/plugin.c-		g_signal_new("enable",
libxfdashboard/plugin.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/plugin.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/plugin.c-		g_signal_new("disable",
libxfdashboard/plugin.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/plugin.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/plugin.c-		g_signal_new("configure",
libxfdashboard/plugin.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/plugin.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/quicklaunch.c-		g_signal_new("selection-add-favourite",
libxfdashboard/quicklaunch.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/quicklaunch.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/quicklaunch.c-		g_signal_new("selection-remove-favourite",
libxfdashboard/quicklaunch.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/quicklaunch.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/quicklaunch.c-		g_signal_new("favourite-reorder-left",
libxfdashboard/quicklaunch.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/quicklaunch.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/quicklaunch.c-		g_signal_new("favourite-reorder-right",
libxfdashboard/quicklaunch.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/quicklaunch.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/quicklaunch.c-		g_signal_new("favourite-reorder-up",
libxfdashboard/quicklaunch.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/quicklaunch.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/quicklaunch.c-		g_signal_new("favourite-reorder-down",
libxfdashboard/quicklaunch.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/quicklaunch.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/stage.c-		g_signal_new("show-tooltip",
libxfdashboard/stage.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/stage.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/stage.c-		g_signal_new("hide-tooltip",
libxfdashboard/stage.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/stage.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/view.c-		g_signal_new("scroll-to",
libxfdashboard/view.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/view.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/view.c-		g_signal_new("child-needs-scroll",
libxfdashboard/view.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/view.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/view.c-		g_signal_new("child-ensure-visible",
libxfdashboard/view.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/view.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/view.c-		g_signal_new("view-activate",
libxfdashboard/view.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/view.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/windows-view.c-		g_signal_new("window-close",
libxfdashboard/windows-view.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/windows-view.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/windows-view.c-		g_signal_new("windows-show-numbers",
libxfdashboard/windows-view.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/windows-view.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/windows-view.c-		g_signal_new("windows-hide-numbers",
libxfdashboard/windows-view.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/windows-view.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/windows-view.c-		g_signal_new("windows-activate-window-one",
libxfdashboard/windows-view.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/windows-view.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/windows-view.c-		g_signal_new("windows-activate-window-two",
libxfdashboard/windows-view.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/windows-view.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/windows-view.c-		g_signal_new("windows-activate-window-three",
libxfdashboard/windows-view.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/windows-view.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/windows-view.c-		g_signal_new("windows-activate-window-four",
libxfdashboard/windows-view.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/windows-view.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/windows-view.c-		g_signal_new("windows-activate-window-five",
libxfdashboard/windows-view.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/windows-view.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/windows-view.c-		g_signal_new("windows-activate-window-six",
libxfdashboard/windows-view.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/windows-view.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/windows-view.c-		g_signal_new("windows-activate-window-seven",
libxfdashboard/windows-view.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/windows-view.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/windows-view.c-		g_signal_new("windows-activate-window-eight",
libxfdashboard/windows-view.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/windows-view.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/windows-view.c-		g_signal_new("windows-activate-window-nine",
libxfdashboard/windows-view.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/windows-view.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
--
libxfdashboard/windows-view.c-		g_signal_new("windows-activate-window-ten",
libxfdashboard/windows-view.c-						G_TYPE_FROM_CLASS(klass),
libxfdashboard/windows-view.c:						G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION,
```

Only "focus-move-first" and "focus-move-last" is missing but could be implemented easily. Maybe I will do it before releasing next unstable version.

3.) I haven't looked at this request yet so I'm not sure if it would fit into XfdashboardFocusManager as the target or if a XfdashboardFocusable should provide such an action. Could you copy this request to a new issue here in GitHub?

**Comment by gwhitney** [comment]
Concerning:
1) Thank you so much! As soon as I have the time, I will update to <master> or to a release with this fix if there is one by that point, and let you know how it goes.
2) Thanks for the tip on how to find actions in the source, but I must confess I do not see "selection-move-next" or "selection-move-previous" in the grep output you posted. Perhaps I am missing something?
3) Separated to #145 as requested.
Very grateful (and impressed) by your feedback,  Glen

**Comment by gmc-holle** [comment]
I do not know what I have read. But you are right, there is no "selection-move-next" or "selection-move-previous" action .... until now ;) Implemented with last commit 0c1fa61833a40976170c5caa881e610563a83427

**Comment by gmc-holle** [comment]
Actions "focus-move-first" and "focus-move-last" to move focus to first or last focusable actor is now implemented with commit 717fd4f43082426bc7262d2fd01f8261369d84a4

So I will close this issue for now. Please feel free to reopen this issue if you have any problem.

**Comment by gwhitney** [comment]
I finally had a chance to clone from git and compile it and try these changes. The new actions for key bindings work nicely, thanks! Also, if I change the relevant line of my theme to
`<focus ref="quicklaunch" selected="true" />`
then indeed xfdashboard starts initially with quicklaunch selected. On the other hand, if I start in daemon mode, and then I resume xfdashboard, change which actor has focus, suspend xfdashboard (say with Esc), and then again resume xfdashboard, I find that the last actor that had focus when I suspended has focus. This behavior seems to be the same whether I set the xfdashboard setting for "Switch to view when resumed" to any of Do Nothing, Windows View, or Applications View. I was seeking a way to specify which actor would have focus _whenever_ xfdashboard resumes, regardless of what had focus before. Is that possible in some way? Please note that the enhancement as it is now is already a big improvement and I am appreciative, was just curious about this particular point.

**Comment by gwhitney** [comment]
Very minor: you say "reopen the issue if I have any questions" but I don't see any way I can alter the status of this issue...

**Comment by gmc-holle** [comment]
OK, I am on the other side of this bug reporting tool ;) I thought you can reopen it as I see this button.

**Comment by gmc-holle** [comment]
Then we need a new configuration like "/switch-to-view-on-resume". Something called "/reselect-focus-on-resume" or "/reselect-theme-focus-on-resume". I see what I can do.

**Comment by gmc-holle** [comment]
It's implemented and works for me so far. I added the property ```/reselect-theme-focus-on-resume``` to xfconf but it is a hidden option. You cannot configure it with xfdashboard's settings application.

To activate this feature use the following command:

```
xfconf-query -c xfdashboard -p /reselect-theme-focus-on-resume -t bool -s true
```

To deactivate is as simple as:

```
xfconf-query -c xfdashboard -p /reselect-theme-focus-on-resume -t bool -s false
```

When setting this option the first time you will need to add ```--create``` as first command-line parameter.

**Comment by gwhitney** [comment]
OK, I had a chance to pull the latest changes and recompile. I set the xfconf property as above and indeed! the dashboard now always comes up with the quick launcher focused. Yay, thank you.

I should mention though that I now get the following messages every time I start xfdashboard, which I never saw before.

`(xfdashboard:23871): xfdashboard-CRITICAL **: xfdashboard_viewpad_find_view_by_id: assertion 'inID && *inID' failed

(xfdashboard:23871): xfdashboard-WARNING **: Cannot switch to unknown view ''`

Finally, I got the git version of xfdashboard compiled in my home directory to find the hot-corner plugin using the environment variable you mentioned in the other issue, so now I am all set to just use the git version until the openSUSE Tumbleweed package catches up to these changes in a future release. Thanks again.

**Comment by gmc-holle** [comment]
You are welcome. I'm glad to hear that it works for you now :) 

I know these message and they should be fixed in latest git. But you have to use change the setting 'Switch to view on resume' to another value and back to the old value using the git version of xfdashboard-settings in the folder 'settings' in git. Then these message should go away - in theory.

I feel free to close this issue now if you don't mind.
