### ISSUE TITLE
focus-move-to action

### ISSUE THREAD

**Issue by gwhitney** [gmc-holle/xfdashboard#145]
Moving this request from #144 to a new separate issue per gmc-holle request:

It would be useful to have an action as follows, but it's not quite clear how it fits into the current framework:

focus-move-to (the idea is to be able to specify a key that always moves directly to a given actor. However, I am not sure in the current XML syntax how the destination actor would be specified, since the source has to specify where the keystroke is accepted from and the target would have to be the focus manager.)

gmc-holle's initial comments on this idea in the previous issue where it was included:

> I haven't looked at this request yet so I'm not sure if it would fit into XfdashboardFocusManager as the target or if a XfdashboardFocusable should provide such an action.

**Comment by gmc-holle** [comment]
It's implemented, so you can use ```focus-move-to``` at your key bindings file. E.g. to move the focus to the quicklaunch actor when you release the key combination Control+Q just add the following line to bindings.xml:

```
<key code="<Ctrl>-q" source="XfdashboardFocusable" target="XfdashboardQuicklaunch" when="released">focus-move-to</key>
```

As you see the target has to be the target actor's class what is clear if I had spend more than just a minute to think about it. Nevertheless it is implemented now and works for me. Could you test latest git?

**Comment by gwhitney** [comment]
Wow, thanks! Will absolutely test the latest git, but I am a bit swamped at the moment, may take a couple days (sorry).

**Comment by gwhitney** [comment]
Dear gmc-holle, 

OK, my time has freed up a bit and I will try to test the latest git now. I want to mention though that I am using OpenSUSE Tumbleweed, which I switched to recently (leaving proprietary macOS behind), and I am currently using xfdashboard from the X11:xfce opensuse repository, which is at version 0.7.1-1.1 (I guess perhaps opensuse packagers have patched it in some way??) and frankly I am a bit unsure of the process to uninstall the package and install the latest git in a way that I will be able to move back to the packaged version once it has moved on to a future release that has these changes. I think I may need to learn how to use the "OpenSUSE Build Server" (OBS), so this process may take me a while as this is the first time I have tried to do this. If you happen to have any advice/pointers on this, I would welcome them. (It's not that I have any worries about being able to build xfdashboard from Git sources, just that xfdashboard is currently installed as six packages and one "application" (!) and I am not yet sure how a build from source interacts with the "zypper" package manager in opensuse.
Thanks and will keep in touch, Glen

**Comment by gmc-holle** [comment]
I'm really sorry but I will not be of any help here as I do not use any distribution based on binary packages. I use Gentoo at all my systems.

But you don't need to create packages and install them just to test (or run regulary) the git version of xfdashboard. For testing purpose I introduced the environment variable XFDASHBOARD_FORCE_NEW_INSTANCE a long time ago. If this environment variable is set when "xfdashboard" is executed it will spawn a temporary secondary (or 3rd or 4th ...) instance, so it does not touch or affect the running main instance.

I use a little bash script to call my git version temporary. Assuming git of xfdashboard is located at ~/xfdashboard this script must be place at ~/xfdashboard_git.sh:

```
#!/bin/bash

PROGDIR=$(dirname "$0")
PROGDIR="${PROGDIR}/xfdashboard"

IS_DEBUG=0
while [ $# -gt 0 ] ; do
  case "$1" in
    --debug|-d)
      IS_DEBUG=1;;
    --)
      shift 1
      break;;
  esac

  shift 1
done

if [ ${IS_DEBUG} -eq 0 ] ; then
  make -C "${PROGDIR}/libxfdashboard" -j4 && \
    make -C "${PROGDIR}/xfdashboard" -j4 && \
    XFDASHBOARD_FORCE_NEW_INSTANCE=1 XFDASHBOARD_THEME_PATH="${PROGDIR}/data/themes/xfdashboard" "${PROGDIR}/xfdashboard/xfdashboard" $@
else
  make -C "${PROGDIR}/libxfdashboard" -j4 && \
    make -C "${PROGDIR}/xfdashboard" -j4 && \
    XFDASHBOARD_FORCE_NEW_INSTANCE=1 XFDASHBOARD_THEME_PATH="${PROGDIR}/data/themes/xfdashboard" LD_LIBRARY_PATH="${PROGDIR}/libxfdashboard/.libs:${LD_LIBRARY_PATH}" gdb -ex run --args "${PROGDIR}/xfdashboard/.libs/xfdashboard" $@
fi

exit $?
```

Just change your working direction to ~/xfdashboard and then call:

```
../xfdashboard_git.sh
```

I hope this could help.

**Comment by gwhitney** [comment]
Sorry to clutter this issue with these minor points, but I don't think I have any direct way of contacting. Thanks for the advice, I didn't think of running an entire separate copy of xfdashboard to test it. So I have cloned the latest git and built it and it runs, but unlike the "system" one, I always get the warning
`xfdashboard-WARNING **: Could not load plugin 'hot-corner': Could not find module for plugin ID 'hot-corner'`
and of course with the git one in (a subdirectory of) my home directory my hot corner to trigger xfdashboard does not work, whereas it does with the system one. Any suggestions on how to get my git xfdashboard to find the hot-corner plugin? In the meantime I will test all of the requests I made and post back here.

**Comment by gwhitney** [comment]
OK, I am happy to report that in the xfdashboard built from a git snapshot today:
1) I can bind keys as shown above to move the focus directly to one component of xfdashboard.
2) If I change the relevant line in the layout xml file to `<focus ref="quicklaunch" selected="true" />` then indeed xfdashboard starts up with the quicklaunch focused. (But I do have one concern about how this is working which I will post to #144 where this was implemented.)
3) Bindings to selection-move-previous and selection-move-next work just fine.

Thank you so much for implementing these enhancements! As far as I am concerned, this issue could be closed.  Glen

**Comment by gmc-holle** [comment]
This little script is far from perfect and just a helper. You can also specify one addition plugin search path with XFDASHBOARD_PLUGINS_PATH but this only helps to load one plugin from git directory as you can specify only one path at this environment variable and at git directory each plugin has its own directory - so finally you can only load one plugin from git.

BTW there are also XFDASHBOARD_BINDINGS_POOL_FILE to specify a different key binding file which should by tried to be loaded first and XFDASHBOARD_THEME_PATH to specify the path (not fie) to xfdashboard.theme of the theme to test.

Last but not least: Thanks you very much for testing :)
