### ISSUE TITLE
version 7.2 doesn't point out wallpaper at the daemon mode

### ISSUE THREAD

**Issue by gnanini** [gmc-holle/xfdashboard#148]
Outside the daemon mode, everything is normal, but on daemon mode the right dock isn't pointing the desktop wallpaper correctly.

**Comment by gmc-holle** [comment]
Could you describe it more precisely? What does "[...] isn't pointing the desktop wallpaper correctly [...]" mean? Wrong image, wrong size or right image but at wrong workspace?

**Comment by gnanini** [comment]
It isn't pointing at all.

**Comment by gnanini** [comment]
well... an image can say more than a thousand words!

<a href="http://www.zimagez.com/zimage/screenshot2017-10-2308-27-22.php">
  <img src="http://www.zimagez.com/miniature/screenshot2017-10-2308-27-22.php" />
</a>

**Comment by gmc-holle** [comment]
Yes, I see. Is it still happening with latest version 0.7.4?

**Comment by gnanini** [comment]
I installed the latest git version and is still happening...

The output of xfdashboard --help says it's on version 0.7.5git.f7e9436

**Comment by gmc-holle** [comment]
Ok, that's bad :'( I will have a look at it.

**Comment by gsantner** [comment]
nope, happening too in current master

**Comment by gnanini** [comment]
I reinstall it and it's working now on archlinux, on daemon mode!

<a href="http://www.zimagez.com/zimage/screenshot2017-10-2717-46-45.php">
  <img src="http://www.zimagez.com/miniature/screenshot2017-10-2717-46-45.php" />
</a>

**Comment by gmc-holle** [comment]
@gnanini Glad to hear that it is working now. I hope you have not reinstalled the whole system ... and not just because of xfdashboard. Have you changed anything? Did you change distribution or are you running a different desktop environment? Did you change the window manager or nothing at all?

@gsantner Do you run a Xfce desktop environment? Do you have any application running providing the X11 root window like `xfdesktop`?

**Comment by gnanini** [comment]
@gmc-holle, I did not reinstall my system, just uninstall xfdashboard and Install it again, because it was upgraded!

My distribution is the same, archlinux, and the window manager is still xfwm4, in fact I'm using the git version, but I was already using it before reinstall xfdashboard... My xfce is pure, if I can say that! but I use others environments!

Oh, just to point out, the middle-click window close plugin is not working! but is a minor issue!

Xfdashboard is running smoothly!

**Comment by gmc-holle** [comment]
@gnanini Sorry to be sooooo late to thank you for your response and testing :)

As it works now I'll close this issue.
