### ISSUE TITLE
cmdline option: Applications menu

### ISSUE THREAD

**Issue by gsantner** [gmc-holle/xfdashboard#150]
Please add a command line option which opens xfdashboard into applications menu (e.g. `--menu applications`). This way one could bind `<Super>A` to `xfdashboard --menu applications`.

There could be also a `--menu windows` option which behaves similary.

**Comment by gmc-holle** [comment]
Hi,

this command-lie option is already available. Just use the parameter "--view" followed by the ID of the view you want to see. Valid IDs are: `builtin.windows` and `builtin.applications`. There might be more valid view IDs if plugins are installed and enabled - but I haven't seen any external plugin so far.

So try the following to command to open xfdashboard with applications menu:

```
xfdashboard --view builtin.applications
```

**Comment by gsantner** [comment]
Can you please note that (all default available/included values) somewhere in the docs?
I search throgh man, --help, every linked document in the README and there was not a single word about what is available (and in this docs: that this and other cmdline options even exist)  :) .

**Comment by gmc-holle** [comment]
Yes, I think that's possible to include the command-line options in the quick'n'dirty user guide at http://goodies.xfce.org/projects/applications/xfdashboard/manual

I will close this issue.

**Comment by gsantner** [comment]
@gmc-holle I'm back on the xfce system. Do you need some info, feedback or debug output on some issue?

(not related to this specific issue)
