### ISSUE TITLE
Configurable count of shown items in search

### ISSUE THREAD

**Issue by gsantner** [gmc-holle/xfdashboard#152]
Currently the search always outputs just 5 items. Would be great to have an option for this in settings to increase this default value. 

EDIT: Something is already there in [code](https://github.com/gmc-holle/xfdashboard/blob/master/libxfdashboard/search-result-container.c#L1301) but there is no UI for it (xfdashboard-settings). Currently only controllable somehow by css of the selected xfdashboard theme?

**Comment by gmc-holle** [comment]
Yes, that's already possible to configure and you have found the right place. Right now it's not very convinient to change this value as you have to copy the theme you use to $HOME/.local/share/themes (or $HOME/.themes/ in the first step. Then you can either change the CSS file directly or you create a new one and add it to the theme definition file `xfdashboard.theme`.

Regardless which way you choose you have to add the following code part to the CSS file (best is at the end):

```
XfdashboardSearchResultContainer
{
    initial-results-size: 10;
}
```

See theming documentation http://xfdashboard.froevel.de/theming-unstable.html#theme-stylable-properties-XfdashboardSearchResultContainer for unstable version (0.7 series) or http://xfdashboard.froevel.de/theming.html#theme-stylable-properties-XfdashboardSearchResultContainer for stable version (0.6 series)

**Comment by gsantner** [comment]
ok thanks. Then heres a real bug:

![grafik](https://user-images.githubusercontent.com/6735650/26872561-42fae8ba-4b77-11e7-8b20-affef402d36f.png)
The show more - button is alwyay shown, even if there are no more results

**Comment by gmc-holle** [comment]
I may sound weird but are you sure that no more results are available? Have you cliick on "Show 5 more results..."? I tried several search terms, added characters to the search term to reduce the number of results and remove characters to increase the number again. At each time to button was shown correctly.

Anyway it will be hard to reproduce the problem as I will not have the exact same number of applications installed as you so I cannot follow the steps you did to reproduce the problem each time. I could add some more debug messages if the problem still persists.

Regards translation: I will accept you request at Transifex.

**Comment by gmc-holle** [comment]
Ah ... and you do not need to copy the whole theme and modify it fit your needs. With latest commit I can create a file `$HOME/.config/xfdashboard/themes/user-<<THEME_NAME>>.css` with the portion of changes you want to apply to theme `<<THEME_NAME>>`. This file will be loaded *after* theme's css files have been loaded.

**Comment by gsantner** [comment]
@gmc-holle : I setted the number of max items to "all" via theme, searched e.g. for firefox. There is just one result, but the "Show 5 more" button is still shown

**Comment by gmc-holle** [comment]
Ok, you've applied the following snippet, didn't you?

```
XfdashboardSearchResultContainer
{
    initial-results-size: 0;
}
```

Then I should reproduce the problem. Will test it later.

**Comment by gsantner** [comment]
exactly

**Comment by gsantner** [comment]
doesnt happen on current HEAD

**Comment by gsantner** [comment]
@gmc-holle 
btw: <https://github.com/gmc-holle/xfdashboard/issues/152#issuecomment-306746672> still happens when settings the initial count to zero (but not at 9999 for example)

**Comment by gmc-holle** [comment]
As said before it will be hard to reproduce as I will have a different environment even if it differs slightly, e.g. numbers of applications installed, the installed applications themselves etc.

I try again to find the source why it will not work  :(

It happens every time again, isn't it? So it is reproducible for you each time?

**Comment by gmc-holle** [comment]
I hope I found it. If I'm right then it was a one-line-fix. So if you can reproduce the problem for sure, can you try latest git with commit a5dc96881907ed6c96acd5c78a0fad80675f3771?

**Comment by gsantner** [comment]
I can confirm that this is fixed, I don't know if exactly that commit was it, but in my version the issue is done 👍 thanks

`Remote instance: xfdashboard-0.7.5git.2461f52`
