### ISSUE TITLE
Compile fails at x11/window-tracker-11.c when GTK+ prior to version 3.22 is installed

### ISSUE THREAD

**Issue by GlebWork** [gmc-holle/xfdashboard#153]
Can you add .deb packages to your release schedule?
I have some issues with compiling both 0.7.3 and 0.7.2 versions.

`CC       x11/libxfdashboard_la-window-tracker-x11.lo
x11/window-tracker-x11.c: In function ‘_xfdashboard_window_tracker_x11_on_screen_size_changed’:
x11/window-tracker-x11.c:1085:6: error: ‘XfdashboardWindowTrackerX11Private {aka struct _XfdashboardWindowTrackerX11Private}’ has no member named ‘needScreenSizeUpdate’
  priv->needScreenSizeUpdate=TRUE;
`

**Comment by gmc-holle** [comment]
Hi,

I do not provide any binary package as I use a distribution build from sources, i.e. Gentoo. So I have to say sorry, that I cannot help you with your request.

On the other side you have found a bug ;) You have GTK+ prior to version 3.22 installed so another code path is used. One line was not correctly wrapped for this case causing this compiler issue. 

Just apply this patch. I should correct the bug.

```
diff --git a/libxfdashboard/x11/window-tracker-x11.c b/libxfdashboard/x11/window-tracker-x11.c
index af788b8..51ca473 100644
--- a/libxfdashboard/x11/window-tracker-x11.c
+++ b/libxfdashboard/x11/window-tracker-x11.c
@@ -1082,7 +1082,9 @@ static void _xfdashboard_window_tracker_x11_on_screen_size_changed(XfdashboardWi
        priv=self->priv;
 
        /* Get new total size of screen */
+#if GTK_CHECK_VERSION(3, 22, 0)
        priv->needScreenSizeUpdate=TRUE;
+#endif
        xfdashboard_window_tracker_get_screen_size(XFDASHBOARD_WINDOW_TRACKER(self), &w, &h);
 
        /* Emit signal to tell that screen size has changed */
```

Or cherry-pick commit 021bf6b1c2a90805f60c3dff0bfde07b7b4eb551 if you use the code from git.

**Comment by GlebWork** [comment]
@gmc-holle Thank you, but could you provide more specific info how to apply this patch on Ubuntu? I need manually correct one file?

**Comment by gmc-holle** [comment]
As you have to correct only one line it is easier to edit the file `libxfdashboard/x11/window-tracker-x11.c` with your favourite text editor. Go to line 1085 - it should be 

```
    priv->needScreenSizeUpdate=TRUE;
```

Add one line before and one line after this one, so it reads at the end:

```
#if GTK_CHECK_VERSION(3, 22, 0)
    priv->needScreenSizeUpdate=TRUE;
#endif
```

It should then compile.

**Comment by GlebWork** [comment]
@gmc-holle Thank you! It helped.

**Comment by gmc-holle** [comment]
You are welcome.
