### ISSUE TITLE
Add Polish translation

### ISSUE THREAD

**Issue by m4sk1n** [gmc-holle/xfdashboard#155]
Some time ago, I started translating xfdashboard to Polish language on Transifex. Will it be included to master?

**Comment by gmc-holle** [comment]
Hi,

my fault. I was too stupid to use the transfex tool "tx" the right way. I was only updating the locales already include at xfdashboard but missed new ones like yours. I have already run this tool with the correct parameters to download new translations also - including yours. xfdashboard now supports 13 locales (it was 8 previously).

I'm sorry that I had ignored your work accidently. Please keep up your work.

I'll close this issue now.
