### ISSUE TITLE
Improve search result order

### ISSUE THREAD

**Issue by gsantner** [gmc-holle/xfdashboard#161]
Currently search results are just ordered plainly. I open e.g. mostly the same application when searching, e.g. xfce systemsettings. here i usually get like 50 results with "settings" and its hard in there to find the right one.

Therefore I would suggest two things maybe improving the flow:

* Order by recently used -> Save a map<desktopfile,date>
* Order by used count -> Map<desktopfile,count>

and Adding an Dropdown to select between alphabetical, used, count in xfdashboard-settings component

**Comment by gmc-holle** [comment]
The "order by used count" is already implement but it cannot be simply turned on via the settings application and it is also not documented (yet) at http://xfdashboard.froevel.de/settings.html or http://xfdashboard.froevel.de/settings-unstable.html

You can define in Xfconf one of three sort modes for the application search. To set a mode use either the graphical settings editor (`xfce4-settings-editor`) or execute the following command in a console:

```
xfconf-query -c xfdashboard -p /components/applications-search-provider/sort-mode -t int -s <<SORT_MODE>>
```

Where `<<SORT_MODE>>` can be:

0 - None (as returned by application search, usually alphabetically sorted)
1 - By names (the more title, description and commands of an application matches the search term the more relevant they are)
2 - By usage (the more this application was launched from xfdashboard the more relevant they are)

What is missing is sorting by recently used. And I haven't decided if it should be implemented.

**Comment by gsantner** [comment]
ah nice :D 
Recently used/count: what you think works best

basically just UI is missing?

**Comment by gsantner** [comment]
`xfconf-query --create -c xfdashboard -p /components/applications-search-provider/sort-mode -t int -s %VALUE%`

**Comment by gmc-holle** [comment]
Yes, UI is missing as well as to mention it in documentation. So far it is a hidden option ;)

**Comment by gmc-holle** [comment]
I think I can close this issue for now. I will add the hidden option to documentation but no UI will be implemented.
