### ISSUE TITLE
Improvements to the source translation

### ISSUE THREAD

**Issue by scootergrisen** [gmc-holle/xfdashboard#163]
Here i will write about things i find in the source translation to be improved.

Should "new" and "a" be switched in this string?
> Adds new a view showing a clock
> Adds a new view showing a clock

**Comment by gmc-holle** [comment]
Yes, that sounds scary :( Fixed with commit 880c74ae8a8a6f11731f30e8daa77eeadd5a2720

**Comment by scootergrisen** [comment]
Suggest using a placeholder for "all applications".

> #: ../data/data/preferences.ui.h:32
> msgid ""
> "When enabled an \"all applications\" menu containing all installed "
> "applications will be shown at applications view"

So it always is the same at the following string if that is what is it suppose to be.

> #: ../libxfdashboard/applications-view.c:533
> #: ../libxfdashboard/applications-view.c:534
> msgid "All applications"

**Comment by gmc-holle** [comment]
As far I can check it, it is not possible -  at least for the source file `../data/data/preferences.ui.h:32`. This is a translatable tooltip text from a UI file created with the tool `glade`. There is AFAIK no way to replace this tooltip text with a placeholder. If you know a way to get a placeholder inserted into the UI file, please tell me. So far this issue gets the state `wontfix`.
