### ISSUE TITLE
Gnome Shell like application list / search

### ISSUE THREAD

**Issue by gsantner** [gmc-holle/xfdashboard#164]
Currently the only implemented search / application list is a vertical list. I would really like it if xfdashboard too would have an design/theme/plugin to display it in a icon-grid like in gnome shell, I think it's a legimitate feature request for a "maybe gnome dashboard like" project 😄. (This doesn't mean in any way it should be the default layout.)

Here's how Gnome Shell is doing it:

Search results:  
![http://www.omgubuntu.co.uk/wp-content/uploads/2017/06/search-list-layout.png](http://www.omgubuntu.co.uk/wp-content/uploads/2017/06/search-list-layout.png) 

Applications page:  
![https://4.bp.blogspot.com/-4MRgtYWxnKE/WIsue9DE1cI/AAAAAAAAYv4/3HXFrzzdEmk6allD0ipBqzaaEuyU9hlFQCLcB/s1920/dash-to-panel_3.png](https://4.bp.blogspot.com/-4MRgtYWxnKE/WIsue9DE1cI/AAAAAAAAYv4/3HXFrzzdEmk6allD0ipBqzaaEuyU9hlFQCLcB/s1920/dash-to-panel_3.png)

I don't know what would suit best to create to make this available  
* Two custom views? (those small switchtable buttons  on top left)
* Theming?
* Option for both, search results and applications view - Layout :: Vertical / Grid?
* Or even - is this already existing in any way and I missed it? :D

**Comment by glolsh** [comment]
@gmc-holle is development stopped?

**Comment by gmc-holle** [comment]
No development is not stopped but stalled as I have moved and besides the work I have to renovate. So I do not have much time left - to be honest it's none.

PS: I had already replied to this issue by mail but it looks like it hasn't arrived yet :( All standard views (application and search view) do already support the vertical list and the icon grid view. It's a theme decision what to use whereby the vertical list is the default. See property `view-mode` for XfdashboardApplicationView and XfdashboardSearchView at the theme documentation (e.g. http://xfdashboard.froevel.de/theming.html#theme-stylable-properties-XfdashboardApplicationsView). Valid values for type `XfdashboardViewMode` are: `list` and `icon`.

PS2: As I really like to have xfdashboard completely customizable - either by themes or plugins - it would make sense to allow plugins to extend the number of possible views. But I have no ideas yet and other issues (and started development branches) have higher priority.

**Comment by glolsh** [comment]
@gmc-holle thanks for your response. Please, take your time.

**Comment by gmc-holle** [comment]
As time moved by I forgot the point here and even the comment do not help to memorize. So please excuse my question:

What do you expect with this issue? If creating a "new" theme with different value (`icon`) for the `view-mode` is not the solution - what should xfdashboard provide?

**Comment by gsantner** [comment]
To whom is this message? :D

**Comment by gsantner** [comment]
How does this icon mode work? I tried to active it but no success yet, and could not found a real example for that. Thats what I tried:

`/home/username/.config/xfdashboard/themes/global.css`:
```
XfdashboardSearchView, XfdashboardSearchView
{
        view-mode: icon;
}
```
and the icon is still in list mode, is this wrong usage?

What I would suggest is the following: To add an setting in `xfdashboard-settings`: View Mode. This has three options -
* By theme (default)
* Icon mode (Grid)
* List Mode (Vertical)

**Comment by gmc-holle** [comment]
NOTE: Please keep in mind that according to the CSS1 specification (http://www.w3.org/TR/2008/REC-CSS1-20080411/#cascading-order) more specific selectors will take precedence over the less specific ones.

That said your `/home/username/.config/xfdashboard/themes/global.css` file has 1) to define at least selectors of same level or have to be more specific and 2) the selectors must be named correctly ;) 

To apply the `icon` view mode to the applications menu you must write `XfdashboardApplicationsView`. You missed an `s` in the actor's name.

`XfdashboardSearchView` does not provide the `view-mode` property because each search provider can specifiy by itself how it will display its results. Each search provider will get its own `XfdashboardSearchResultContainer` which will provide this property. Regarding to the default theme `xfdashboard` a well specific selector (`XfdashboardSearchView XfdashboardSearchResultContainer`) is already defined so you have to match it or you have to define a more specific selector.

So your file has to look as this to get applied:

```
XfdashboardApplicationsView,
XfdashboardSearchView XfdashboardSearchResultContainer
{
        view-mode: icon;
}

XfdashboardSearchView XfdashboardSearchResultContainer XfdashboardButton.result-item.view-mode-icon
{
        button-style: both;
}
```

The last selector is needed as the default theme misses to set the `button-style` in icon view mode resulting in button only showing the text but no icon. This will be corrected with the next commit.

I will not include a setting for this as this a theme desing. Settings should only affect non-theme related items in xfdashboard or should provide a setting for performance reasons - and maybe privacy reasons.

**Comment by gsantner** [comment]
Thank you very much for the css above, that's working! :smile: 

Still, we can't await from users to search somewhere deep in the issues to find some manually-to-add css lines to get some shell-alike experience (my opinion). Shall I send a PR to add these lines to docs at least (for putting it into global.css)?

First things I noticed: 

## 1
Pressing left/right on the most-left/most-right position doesn't move to column0 and next row (or first row if end), instead it just moves to beginning of the current line:

![grafik](https://user-images.githubusercontent.com/6735650/38220753-473c5994-36dc-11e8-92e4-35626ea1b950.png)
pressing right (expected position: pidgin)
![grafik](https://user-images.githubusercontent.com/6735650/38220766-5c4880c4-36dc-11e8-938e-749ba95e1e5c.png)

## 2
Sizing: The size of the elements, 


![grafik](https://user-images.githubusercontent.com/6735650/38220840-c55be4ca-36dc-11e8-813d-e284055e7f35.png)
Thanks for the css above, that's working in general.

Still, we can't await from users to search somewhere deep in the issues to find maybe some manually-to-add css lines to get some shell-alike experience in my opinion.

First things I noticed: 

## 1
Pressing left/right on the most-left/most-right position doesn't move to `row->next, col=0`, instead it just moves to beginning of the current line:

![grafik](https://user-images.githubusercontent.com/6735650/38220753-473c5994-36dc-11e8-92e4-35626ea1b950.png)
pressing right (expected position: pidgin)
![grafik](https://user-images.githubusercontent.com/6735650/38220766-5c4880c4-36dc-11e8-938e-749ba95e1e5c.png)

## 2
Grid size: It seems like the amount of grid columns is depending on the amount of search results.  Is there a way to turn this off? - to set e.g. a fixed amount of columns of 5. So there are always 5 columns, and results always starting on top left.


![grafik](https://user-images.githubusercontent.com/6735650/38220840-c55be4ca-36dc-11e8-813d-e284055e7f35.png)
![grafik](https://user-images.githubusercontent.com/6735650/38220848-d036a218-36dc-11e8-9101-7b1c06dff199.png)

**Comment by gmc-holle** [comment]
I know, long time no see. I'll try to get more responsive again but free time is still rare :(

> Still, we can't await from users to search somewhere deep in the issues to find some manually-to-add css lines to get some shell-alike experience (my opinion). Shall I send a PR to add these lines to docs at least (for putting it into global.css)?
Oh yes, please or edit the wiki pages for xfdashboard at https://goodies.xfce.org/projects/applications/xfdashboard/start directly if you have the permission.

Regarding 1.) Yes, that's intended but I think I could get it configurable. Either by apply a user CSS file or a setting in xfconf. Nevertheless that request should go into a separate issue.

Regarding 2.) That's right. The layout manager used to display the results in a grid determine the largest one and calculates the best fit in column and rows from that one. Again I think I could get it configurable but this time I know it will be a CSS option. Sadly again that should also go into a separate issue as it will be an enhancement feature.

**Comment by gsantner** [comment]
@gmc-holle do you have an recommendation for `global.css` where I could set e.g. margin/padding of result list so it e.g. 20% left and 20% right is not filled with results? don't know if that is possible with css

**Comment by nonamedotc** [comment]
I am late to the party here (but have been following with interest), but is the plan to expose this option as a dropdown in xfdashbaord settings?

Option A - list (default)
Option B - Grid

Thanks for the great work!

**Comment by gmc-holle** [comment]
@gsantner Puhh .... but yes you can set margins. All actors provide the properties `margin-left`, `margin-right`, `margin-top` and `margin-bottom` but it takes a number of pixels - not percentage. So something like this could work but I haven't tested:

```
XfdashboardSearchView XfdashboardSearchResultContainer .result-item
{
    margin-left: 20;
    margin-right: 20;
}
```

If you really want to use percentage then bind constraints are needed and needed to be added to the result item actors. But that will only be possible when #130 will be implemented some day.

**Comment by gmc-holle** [comment]
@nonamedotc You are never too late :P But no, I will not expose this as an option in the settings but configurable via user CSS files as mentioned here (https://github.com/gmc-holle/xfdashboard/issues/164#issuecomment-376394708). The idea is that the theme designer defines the look of xfdashboard and maybe he wants the icon or the list mode and will therefore provide more visual information for the mode he selected. If now an option in the settings override the theme's decision the visual appereance may be distorted as the theme designer has not set any data for this mode.

An option will trigger this issue more often and easier than a user CSS file which needs to be created and I hope the user knows what he does ;)

**Comment by gsantner** [comment]
thanks for hint, gonna try

**Comment by gsantner** [comment]
Just for refereence, these are my modifications related to this (for 1920x1080):
```
XfdashboardApplicationsView,                                                                                                                                            
XfdashboardSearchView XfdashboardSearchResultContainer 
{ 
    view-mode: icon; 
} 
 
XfdashboardSearchView XfdashboardSearchResultContainer XfdashboardButton.result-item.view-mode-icon 
{ 
    button-style: both; 
} 
 
XfdashboardApplicationsView XfdashboardDynamicTableLayout, 
XfdashboardSearchView XfdashboardSearchResultContainer XfdashboardDynamicTableLayout 
{ 
    fixed-columns: 4; 
} 
 
XfdashboardSearchView XfdashboardSearchResultContainer XfdashboardButton.result-item.view-mode-icon 
{ 
    icon-size: 128.0; 
} 
 
XfdashboardSearchResultContainer 
{ 
    initial-results-size: 40; 
    margin-left: 350; 
    margin-right: 350; 
} 
 
XfdashboardTextBox 
{ 
    text-font: "Cantarell 15"; 
    margin-left: 500; 
    margin-right: 600; 
} 
```

![grafik](https://user-images.githubusercontent.com/6735650/40356817-8580b33a-5dba-11e8-9c67-86f8db6cf35c.png)

**Comment by gmc-holle** [comment]
:)

As this issue was split into two new issues and both are solved I will close this issue.
