### ISSUE TITLE
xfdashboard doesn't include all open windows

### ISSUE THREAD

**Issue by nkkollaw** [gmc-holle/xfdashboard#166]
When I launch xfdashboard, it only shows a few windows in the overview, although I have many more open.

On my system, it seems to ignore Google Chrome, Electron-based apps, gnome-terminal, and more.

**Comment by nkkollaw** [comment]
I'm using Xfce 4.13 with Xubuntu Core on Ubuntu Bionic Minimal.

The window manager is xfwm4, 1 workspace.

Xfdashboard version is 0.6.1.

**Comment by gmc-holle** [comment]
Strange, at least with `xfwm4` window manager it should work :( Although version 0.6.1 is a stable version, is there any chance that you can switch to a development version of the 0.7 series? Best would be the latest version 0.7.4

**Comment by nkkollaw** [comment]
¯\_(ツ)_/¯

**Comment by gmc-holle** [comment]
Hmmm ... They are completely missed? Or do you see any "iconified" windows? That means just a rectangle with in big icon in it.

**Comment by gmc-holle** [comment]
Can you tell me which version of package ```libwnck``` is installed?

**Comment by nkkollaw** [comment]
Hello! I installed and tested again.

The problem still occurs. In particular, I have 5 open windows in Chrome, and it only shows 3.

This is libwnck:

```
gir1.2-wnck-1.0/bionic,now 1:2.30.7-5.1ubuntu1 amd64 [installed,automatic]
  GObject introspection data for the WNCK library

libgnome2-wnck-perl/bionic 0.16-3build4 amd64
  Perl interface to the Window Navigator Construction Kit

libwnck-3-0/bionic,now 3.24.1-2 amd64 [installed,automatic]
  Window Navigator Construction Kit - runtime files

libwnck-3-common/bionic,bionic,now 3.24.1-2 all [installed,automatic]
  Window Navigator Construction Kit - common files

libwnck-3-dev/bionic,now 3.24.1-2 amd64 [installed]
  Window Navigator Construction Kit - development files

libwnck-common/bionic,bionic,now 1:2.30.7-5.1ubuntu1 all [installed,automatic]
  Window Navigator Construction Kit - common files

libwnck-dbg/bionic 1:2.30.7-5.1ubuntu1 amd64
  Window Navigator Construction Kit - debugging symbols

libwnck-dev/bionic,now 1:2.30.7-5.1ubuntu1 amd64 [installed]
  Window Navigator Construction Kit - development files

libwnck-doc/bionic,bionic 1:2.30.7-5.1ubuntu1 all
  Window Navigator Construction Kit - documentation files

libwnck22/bionic,now 1:2.30.7-5.1ubuntu1 amd64 [installed,automatic]
  Window Navigator Construction Kit - runtime files
```
xfdashboard is 0.6.1.

:-)

**Comment by gmc-holle** [comment]
Nothing unusual and for me it works with xfdashboard 0.6.1, e.g. Google Chrome windows are shown. Do you run xfdashboard as daemon? Are you sure xfdashboard 0.6.1 is started? Do you have any other version of xfdashboard installed which could interfer?

**Comment by gsantner** [comment]
Can you do run `xfdashboard --version` (paste output here), and after that run xfdashboard using the same executable? Had it too that `/usr/local/bin/xfdashboard` and `/usr/bin/xfdashboard` where installed.

I tried to reproduce this, but all windows show up (well sometimes with stripes, but they always, all, show up)

**Comment by nkkollaw** [comment]
@gsantner sorry, I have since moved to a new install.

I can't help reproduce the issue, but if it hasn't been reported by other people, I guess it's OK.

:-)
