### ISSUE TITLE
grid size problems

### ISSUE THREAD

**Issue by gsantner** [gmc-holle/xfdashboard#168]
#164 Grid size: It seems like the amount of grid columns is depending on the amount of search results.  Is there a way to turn this off? - to set e.g. a fixed amount of columns of 5. So there are always 5 columns, and results always starting on top left.

![grafik](https://user-images.githubusercontent.com/6735650/38220840-c55be4ca-36dc-11e8-813d-e284055e7f35.png)
![grafik](https://user-images.githubusercontent.com/6735650/38220848-d036a218-36dc-11e8-9101-7b1c06dff199.png)

**Comment by gmc-holle** [comment]
Thanks for the new issue. I have already an idea how to improve it. Stay tuned ;)

**Comment by gsantner** [comment]
@gmc-holle Thanks! works fine here!
