### ISSUE TITLE
Add more translations

### ISSUE THREAD

**Issue by f2404** [gmc-holle/xfdashboard#171]
Currently, xfdesktop offers only 14 translations. While a typical Xfce component provides many more: e.g., xfce4-terminal provides 55 translations via transifex.

**Comment by gmc-holle** [comment]
Hi. I'm really happy to provided at least 14 translations. It could be more less. But I cannot add more translation if only these translation were done by the hard-working translator. If you could motivate more translator of languages which are not available yet please guide them to https://www.transifex.com/xfdashboard/xfdashboard/

But honestly: It's nothing I could "fix" as coder. So please understand that I mark this issue as "wontfix".

**Comment by f2404** [comment]
Hi, thanks for your answer. I've just requested Russian to be added to the translations list on transifex. Is that you or someone else who approves the requests?

I guess I'm just wondering why this project is not being translated alongside other xfce projects. Xfce has a lot of translations and translators working on them, so by adding xfdashboard to the list you'd benefit from that for free.
