### ISSUE TITLE
Blurred icons / wrong size

### ISSUE THREAD

**Issue by gsantner** [gmc-holle/xfdashboard#176]
I'm currently running xfdashboard-0.7.5git.1940b1a and seeing blurry icons at some launchers for some time now, probably since last git build. I see normal-unblurry icons in whiskermenu and panel, so it should not be a problem of icon theme or xfce itself. 

Most icons in my sets are svg. Those below are for sure, so this is no image source problem.

Let me know if more information on something is needed

![screenshot_20181103-214151](https://user-images.githubusercontent.com/6735650/47957172-716d6400-dfb1-11e8-8802-ea25f40b88c8.png)

**Comment by gmc-holle** [comment]
Can you tell paste the content of the desktop file for "Systemeinstellungen (XFCE)" or "Druckeinstellungen"? As I see these both have problems with blurry icons, right? And these icons are SVG image files?

**Comment by gsantner** [comment]
@gmc-holle 

`/usr/share/applications/system-config-printer.desktop` - unmodified default launcher

[system-config-printer.desktop.txt](https://github.com/gmc-holle/xfdashboard/files/2610722/system-config-printer.desktop.txt)

But it seems more like xfdashboard somehow isn't using the iconset accordingly. Seems to be somehow a mix out of the iconset and some other icons. When looking at `Druckeinstellungen` at whiskermenu and at `thunar` they appear correctly and even more noticed they use other icon. Didn't notice that at system settings because xfdashboard and all other use the same, hehe.


![screenshot_20181123-133506](https://user-images.githubusercontent.com/6735650/48944011-51342380-ef25-11e8-9aa5-7e3fa220d58e.png)

![screenshot_20181123-133517](https://user-images.githubusercontent.com/6735650/48944015-52fde700-ef25-11e8-8103-c507b9e40fba.png)
![screenshot_20181123-133825](https://user-images.githubusercontent.com/6735650/48944026-5ee9a900-ef25-11e8-8c73-5f77d18129d8.png)

**Comment by gmc-holle** [comment]
Maybe because I haven't seen this difference here. I'm interested at the name of the iconsets you use and maybe which version and which one work and which one does not work. Also the version of the following libraries could help: gtk+, garcon, gdk-pibux, glib and glib-gio (if it is a seperate package).

**Comment by gsantner** [comment]
Closing this it seems not to be reproduceable.
Iconset is humantiy with some additional custom application svgs.
