### ISSUE TITLE
(question) Is there a way to arrange the desktops in a grid? 

### ISSUE THREAD

**Issue by Chrysostomus** [gmc-holle/xfdashboard#179]
Greetings and thank you for this amazing piece of software!

I'm trying use xfdashboard as desktop switcher for bspwm, and I have disabled other ui elements besides the desktop switcher. I was wondering if it is possible to arrange the desktops in a 2x2 or 3x3 grid instead of straight vertical stack?

**Comment by gmc-holle** [comment]
Hi,

Glad to hear that xfdashboard seems to work with bspwm now. The last time I heard of this combination was an issue with a bug report here.

Regarding your question: No, it will not be possible as the current workspace selector (that thing at the right side) is still hard-coded in its layout. Even adding a `<layout>` block to the workspace selector in the layout file `xfdashboard.xml` will not help and I expect more trouble. Sorry. 

If someday issue #130 is solved then it would be possible. But as time not available at the moment I do not expect it anytime soon :(

**Comment by Chrysostomus** [comment]
Thank you for your response and time! =)
