### ISSUE TITLE
HowTo build on Xfce-4.14pre3?

### ISSUE THREAD

**Issue by franksawar** [gmc-holle/xfdashboard#182]
Hiya,

I've tried to build xfdashboard on Xfce 4.14pre3, 
[xfdashboard-build.txt](https://github.com/gmc-holle/xfdashboard/files/3485702/xfdashboard-build.txt)

Is there any chance to fix it with a patch etc?

Frank

**Comment by gmc-holle** [comment]
Hi,

you clone the GIT repository? Was the target folder clean? Then you have to run autogen.sh before configure&make, although you should have done it already or the configure script is missing usually.

Or try "make distclean", re-run autogen.sh, configure and make.

The last resort I know would be to pass "--enable-maintainer-mode" to the configure script.

I hope it helps.

Cheers
Stephan

**Comment by gmc-holle** [comment]
Closing as no feedback.
