### ISSUE TITLE
Remove release descriptions from xfdashboard.appdata.xml.in

### ISSUE THREAD

**Issue by scootergrisen** [gmc-holle/xfdashboard#183]
Maybe not worth having translators translate all the old release descriptions in https://github.com/gmc-holle/xfdashboard/blob/master/data/appdata/xfdashboard.appdata.xml.in

If some should be translated it could be only the new ones and not old stuff that users might never see anyway.

**Comment by gmc-holle** [comment]
Hi,

That was out of my mind but your correct. For translators it is not friendly to keep all the old entries. They have been removed with commit 6d29d10f82fdcb091f9a37e6cbbdac0c256f918f

Thanks
Stephan
