### ISSUE TITLE
Missing galician translation

### ISSUE THREAD

**Issue by damufo** [gmc-holle/xfdashboard#185]
Hello,
Please add the translation of Galician.
It is 100%.
![Captura de pantalla_2019-11-29_16-37-52](https://user-images.githubusercontent.com/4057369/69879047-c4a20b00-12c6-11ea-9c4f-6cfecda2e593.png)

**Comment by damufo** [comment]
https://www.transifex.com/xfdashboard/xfdashboard/dashboard/

**Comment by gmc-holle** [comment]
As mentioned in Bugzilla I was too stupid to use the transifex client with the correct parameters to fetch also new translations. So I missed it. I'm very sorry.

Galician translation was included with commit de9960dbf6c37147f8b433c687f8fbe61ed70764
