### ISSUE TITLE
Icons vision

### ISSUE THREAD

**Issue by AndersonGI** [gmc-holle/xfdashboard#189]
Allow applications to be seen as icons on grid instead of a list

**Comment by gmc-holle** [comment]
Hi,

Yes, that is possible. As explained in commit 7be223df1fc3378691ee851dc7fcc0de3ea312d7 you can either define a user-stylesheet globally that is applied to each the theme or a theme-dependent user-stylesheet.

I think you want the application icons in a grid regardless of theme you selected, then create the file `$HOME/.config/xfdashboard/themes/global.css` and insert the following text:

`XfdashboardApplicationsView
{
        view-mode: icon;
}`

Do not forget to restart xfdashboard as daemon or as standalone application to get your changes applied.

Regards,
Stephans
