### ISSUE TITLE
suppourt for manjaro xfce arm.

### ISSUE THREAD

**Issue by DarkPhoenix2005** [gmc-holle/xfdashboard#190]
i am using manjaro xfce on an arm64 and installing it with yay gives me architecture error. 
```bash 
:: (1/1) Parsing SRCINFO: xfdashboard
 -> The following packages are not compatible with your architecture:
  xfdashboard
==> Try to build them anyway? [Y/n] 
```

plz add suppaurt for manjaro arm ...

**Comment by gmc-holle** [comment]
Hi DarkPhoenix2005,

Sorry, but that's the job of the package maintainer at Manjaro. Here you will only find the sources to compile the binaries for the packages to install. Please fill this issue at Manjaro and ask there for support.

Greetings
Stephan
