### ISSUE TITLE
hot corners only on main monitor

### ISSUE THREAD

**Issue by pidlug** [gmc-holle/xfdashboard#191]
I defined top left hot corner to mimick gnome-shell. It works fine, but only on main display. Second display's corner does not work. Is it normal behavior, or there is something which prevent it working (like different resolution of monitors or layout)?

**Comment by gmc-holle** [comment]
Hi,

yes, the plugin is designed to work on primary monitor only. Do you expect it should also work if your pointer (mouse) is also at the top left corner of your other monitors?

Greetings
Stephan

**Comment by pidlug** [comment]
Yes, with my setup I would prefer it works same on both displays.

Regards
Piotr

W dniu czw, 22.10.2020 o godzinie 06∶30 -0700, użytkownik gmc-holle
napisał:

**Comment by gmc-holle** [comment]
Hi Piotr,

Sorry, took some time but it was implemented in latest git (commit 24c32a73beebb071590ea97fa3b2f03c74fc57e7) and will be officially available with next development release. I hope it works as I do not have a multi-monitor setup anymore.

Regards
Stephan

**Comment by pidlug** [comment]
Hi Stephan
Great! I compiled git version and it works well so far - on my two monitor setup. Thank you!
Here is the Polish translation:
"Primary monitor only"
"Tylko monitor główny"

Greetings
Piotr
