### ISSUE TITLE
Move to secondary screen using keyboard only

### ISSUE THREAD

**Issue by antonioprates** [gmc-holle/xfdashboard#194]
I will put this more as a question, but could be an issue: is there a way (keybinding) to navigate to the secondary monitor only using the keyboard?

I even tried to play around with the focusable ids on both `xfdashboard.xml` and `xfdashboard-secondary.xml` but could never find a way where I wouldn't have to use the mouse to select a window on the secondary monitor.

**Comment by gmc-holle** [comment]
Hi,

do you want to move the focus to the secondary screen by pressing TAB (default key for moving the focus) or do you want to move a window to the secondary screen using the keyboard?

If it is the first one, moving the focus to secondary screen, then it should work already if the theme you are using defines the section <focuables> at its XML file for the secondary screen.

If it is the latest one, moving a window, then there is no action available to do this at moment and I have also no idea how to implement it well.

But first question is: What did you mean? ;)

Regards,
Stephan

**Comment by antonioprates** [comment]
I want to focus on the secondary screen with TAB, which you say should be working, but did not work for me. Maybe because one monitor is the laptop and the other is an external monitor, and they have different resolutions....

I am using the default theme with some modifications to strip off all that is not the windows. As I wanted a really a minimalist window selector and all the other features, felt like clutter to me.

[xfdashboard.xml.txt](https://github.com/gmc-holle/xfdashboard/files/7106327/xfdashboard.xml.txt)
[xfdashboard-secondary.xml.txt](https://github.com/gmc-holle/xfdashboard/files/7106329/xfdashboard-secondary.xml.txt)

It's late here, but tomorrow I will remove the official package (from Manjaro repo) and try to build from latest source using AUR and see if there is anything difference. Will add more details here. Please, let me know if there is any logs I should look at or a way I can try to better debug why it wouldn't work for me, since TAB should take me to other focusables.

**Comment by antonioprates** [comment]
This is me pressing TAB many times using the original xfdashboard-dark theme. As you can see it only cycles over focusables on the right screen (laptop)...

https://user-images.githubusercontent.com/26195023/132086161-91c81267-e02a-425d-90e3-18e6fc05d4fc.mp4

**Comment by gmc-holle** [comment]
Yes, there was a bug when I optimized the stage loading function which registers all focusable actors of a stage. Because of this bug only these ones were registered which are on the primary monitor. Should be fixed with commit 5b0097fd581e8e082a2dfee928137371d4458c65 and will be in the next release.
