### ISSUE TITLE
Option to disable QuickLaunch or WorkspaceSelector

### ISSUE THREAD

**Issue by DominicusPurple** [gmc-holle/xfdashboard#201]
Im not suggesting completely remove these features!
Maybe 2 toggles in the settings app, one for quicklaunch and the other for workspaceselector.
Some people dont use workspaces, so why have them take almost half of the screen?
Some people dont pin apps to quicklaunch, so why have it there when there are window previews?

**Comment by gmc-holle** [comment]
Hi,

that is already easily possible although there is no option in the settings. Just create an a file at *$HOME/.config/xfdashboard/themes/global.css* (loaded by all themes) or at *$HOME/.config/xfdashboard/themes/user-[THEME_NAME].css* (only loaded by the theme [THEME_NAME]) with the following content:

```
#quicklaunch, #workspace-selector:
{
  visibility: false;
}
```

Setting "visibility" to false is similar to "display: none;" for CSS of HTML.

Regards,
Stephan

19.06.2022 12:58:38 DominicusPurple ***@***.***>:
