### ISSUE TITLE
no previews for some windows

### ISSUE THREAD

**Issue by rkitover** [gmc-holle/xfdashboard#202]
I currently have firefox, kitty, virt-manager, skype, and steam running on my first desktop.

I am using LXQT and Openbox.

When I open the overview screen with `xfdashboard -t`, I see the window previews for kitty, firefox and virt-manager but not skype and steam. For those two, I just see a giant version of the window icon.

Also when I start the daemon with `xfdashboard -d` I see this message:

```console
(xfdashboard:215261): xfdashboard-WARNING **: 01:39:09.389: Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined
```

This is xfdashboard version `0.9.90` from Gentoo.

If this can be fixed, I'm happy to do a PR in the appropriate place.

**Comment by rkitover** [comment]
I see how this happens now. Any window that I have minimized in Openbox/lxqt shows the window icon, but if the window is open the preview works fine.

**Comment by gmc-holle** [comment]
That's a known limitation of X and the window managers. As soon as window is minimized, it is also unmapped and you cannot get any image of it. Because of that you'll find an option in xfdashboard setting called "Enable workaround for minimized windows" and an option with choices for the priority, i.e. how fast the images of all unmapped windows should be retrieved via the workaround.

**Comment by rkitover** [comment]
Thank you for the explanation, I'm sorry I didn't see that there's a GUI configuration app for this with this setting.

Doesn't work very well for me though, I just see an empty rectangle with a black border for most minimized windows.

Anything we can do to improve this situation? Things like KDE and Gnome have no problems doing this.

**Comment by rkitover** [comment]
Actually I'm wrong about that, I just noticed that KDE does not show minimized windows in app overview either.
