### ISSUE TITLE
[Question] How to hide the search bar and the app list button using the CSS?

### ISSUE THREAD

**Issue by benyaminl** [gmc-holle/xfdashboard#205]
Hello, I want to ask kind of dumb question, is there anyway to hide the search bar, and only show th desktop and the opened apps? Is that possible? Thank you

**Comment by gmc-holle** [comment]
Hi,

this approach is very similar to the one describe at #201 and yes, that is already easily possible although there is no option in the settings. Just create an a file at *$HOME/.config/xfdashboard/themes/global.css* (loaded by all themes) or at *$HOME/.config/xfdashboard/themes/user-[THEME_NAME].css* (only loaded by the theme [THEME_NAME]) with the following content:

```
#searchbox
{
  visibility: false;
}
```

Setting "visibility" to false is similar to "display: none;" for CSS of HTML.

Regards,
Stephan
