### ISSUE TITLE
Add support for keyboard shortcuts in windows view. 

### ISSUE THREAD

**Issue by rhabbachi** [gmc-holle/xfdashboard#35]
Hi,

It would be great to be able to select a windows with a keyboard shortcut when viewing the windows grid when in windows view. For example when in windows view mode pressing a modifier will display shortcuts (a numbers or a character sequence) over each window, typing the displayed shortcut will activate the window.

Thank you for making xfdashboard. Using it everyday!

**Comment by gmc-holle** [comment]
Now key and mouse binding configuration is implemented at their basics this issue should be resolved for next stable release.

**Comment by gmc-holle** [comment]
Good news. Its implemented now. But to be honest I do not know if this should be activated by default or if the user (e.g. you) must activate it by creating an own bindings.xml

But it's implemented in latest commit 95357acb8b7a19f5a8cc9700d1550c5d8962deea

Issue closed.
