### ISSUE TITLE
Segfault in Arch with i3

### ISSUE THREAD

**Issue by linkaross** [gmc-holle/xfdashboard#37]
hi there

starting xfdashboard (both prod and dev packs) are aborting with segfault on my Arch desktop running i3 4.8:

[ 1470.169713] xfdashboard[23550]: segfault at 18 ip 00000000004383ce sp 00007fff5c586000 error 4 in xfdashboard[400000+9a000]

**Comment by gmc-holle** [comment]
Do you still face this problem or do you use newer version which have fixed this problem for you? Or do you not using xfdashboard anymore? In any case I would be happy to hear if this bug should stay open or can be closed ;)

**Comment by gmc-holle** [comment]
I assume this issue has been solved. Closing issue
