### ISSUE TITLE
Add icons of running applications

### ISSUE THREAD

**Issue by alejandro-perez** [gmc-holle/xfdashboard#39]
Hi! Great app! It's almost exactly what I was looking for!

One thing I miss from GS is having a list of icons of the running applications. Clicking on it will transport you have the same result than clicking on the respective window thumbnail. I guess it is difficult if there are more than one instance. Just asking...

Regards

**Comment by gmc-holle** [comment]
Implemented (basic but working at Linux) with commit a0e9e8919b310cfed7967bf23c62a867290ca436

**Comment by gmc-holle** [comment]
Needs more testing

**Comment by alejandro-perez** [comment]
Hi!

It is great having this functionality on board!
I have tested it and worked well for thunderbird and chromium. Besides showing a check alongsinde the icon, is there anything else I can do with it? It would be great to being able to move to the running instance.

But I have opened several terminal windows, thunar, geany, ... and none of them worked :(.

I'll keep testing nonetheless.

Awesome work!

**Comment by gmc-holle** [comment]
As I said it is a basic implementation and it needs lots of testing. But I'm confused because this basic implementation discovered xfce-terminal, firefox, geany, thunar etc. without any problem.

I have kept turned on the debug message. So if you run xfdashboard in a terminal you should get lots of output telling you and me which windows were found and how (or not) the correponding application was found. Could you run xfdashboard (in non-daemon mode) in a terminal and send me the output?

**Comment by alejandro-perez** [comment]
Here you are the log output (where it seems to detect them) and the screenshot of the result, where you can see an xfce4-terminal and thunar window running. 
```
** e.g.: G_MESSAGES_DEBUG=xfdashboard xfdashboard
xfdashboard-Message: _xfdashboard_application_tracker_get_desktop_id_from_environment: Enviroment set at /proc/11531/environ is 2833 bytes long for window 'xfdashboard'
xfdashboard-Message: _xfdashboard_application_tracker_get_desktop_id_from_environment: Resolved enviroment variables of window 'xfdashboard' to desktop ID '<nil>'
xfdashboard-Message: _xfdashboard_application_tracker_get_desktop_id_from_window_names: Resolved window names of 'xfdashboard' to desktop ID '<nil>'
xfdashboard-Message: _xfdashboard_application_tracker_on_window_opened: Could not resolve window 'xfdashboard' to any desktop ID
xfdashboard-Message: _xfdashboard_application_tracker_get_desktop_id_from_environment: Enviroment set at /proc/11368/environ is 1501 bytes long for window 'Nueva pestaña - Chromium'
xfdashboard-Message: _xfdashboard_application_tracker_get_desktop_id_from_environment: Resolved enviroment variables of window 'Nueva pestaña - Chromium' to desktop ID '<nil>'
xfdashboard-Message: _xfdashboard_application_tracker_get_desktop_id_from_window_names: Resolved window names of 'Nueva pestaña - Chromium' to desktop ID 'chromium.desktop'
xfdashboard-Message: _xfdashboard_application_tracker_on_window_opened: Window 'Nueva pestaña - Chromium' belongs to desktop ID 'chromium.desktop'
xfdashboard-Message: _xfdashboard_application_tracker_get_desktop_id_from_environment: Enviroment set at /proc/11104/environ is 1403 bytes long for window 'alex@vaioalex: ~'
xfdashboard-Message: _xfdashboard_application_tracker_get_desktop_id_from_environment: Resolved enviroment variables of window 'alex@vaioalex: ~' to desktop ID '<nil>'
xfdashboard-Message: _xfdashboard_application_tracker_get_desktop_id_from_window_names: Resolved window names of 'alex@vaioalex: ~' to desktop ID 'xfce4-terminal.desktop'
xfdashboard-Message: _xfdashboard_application_tracker_on_window_opened: Window 'alex@vaioalex: ~' belongs to desktop ID 'xfce4-terminal.desktop'
xfdashboard-Message: _xfdashboard_application_tracker_get_desktop_id_from_environment: Enviroment set at /proc/11104/environ is 1403 bytes long for window 'alex@diffie: ~'
xfdashboard-Message: _xfdashboard_application_tracker_get_desktop_id_from_environment: Resolved enviroment variables of window 'alex@diffie: ~' to desktop ID '<nil>'
xfdashboard-Message: _xfdashboard_application_tracker_get_desktop_id_from_window_names: Resolved window names of 'alex@diffie: ~' to desktop ID 'xfce4-terminal.desktop'
xfdashboard-Message: _xfdashboard_application_tracker_on_window_opened: Window 'alex@diffie: ~' belongs to desktop ID 'xfce4-terminal.desktop'
xfdashboard-Message: _xfdashboard_application_tracker_get_desktop_id_from_environment: Enviroment set at /proc/19924/environ is 1403 bytes long for window 'Bandeja de entrada - UM - Mozilla Thunderbird'
xfdashboard-Message: _xfdashboard_application_tracker_get_desktop_id_from_environment: Resolved enviroment variables of window 'Bandeja de entrada - UM - Mozilla Thunderbird' to desktop ID '<nil>'
xfdashboard-Message: _xfdashboard_application_tracker_get_desktop_id_from_window_names: Resolved window names of 'Bandeja de entrada - UM - Mozilla Thunderbird' to desktop ID 'thunderbird.desktop'
xfdashboard-Message: _xfdashboard_application_tracker_on_window_opened: Window 'Bandeja de entrada - UM - Mozilla Thunderbird' belongs to desktop ID 'thunderbird.desktop'
xfdashboard-Message: _xfdashboard_application_tracker_get_desktop_id_from_environment: Enviroment set at /proc/490/environ is 1333 bytes long for window 'Escritorio'
xfdashboard-Message: _xfdashboard_application_tracker_get_desktop_id_from_environment: Resolved enviroment variables of window 'Escritorio' to desktop ID '<nil>'
xfdashboard-Message: _xfdashboard_application_tracker_get_desktop_id_from_window_names: Resolved window names of 'Escritorio' to desktop ID '<nil>'
xfdashboard-Message: _xfdashboard_application_tracker_on_window_opened: Could not resolve window 'Escritorio' to any desktop ID
xfdashboard-Message: _xfdashboard_application_tracker_get_desktop_id_from_environment: Enviroment set at /proc/486/environ is 1333 bytes long for window 'xfce4-panel'
xfdashboard-Message: _xfdashboard_application_tracker_get_desktop_id_from_environment: Resolved enviroment variables of window 'xfce4-panel' to desktop ID '<nil>'
xfdashboard-Message: _xfdashboard_application_tracker_get_desktop_id_from_window_names: Resolved window names of 'xfce4-panel' to desktop ID '<nil>'
xfdashboard-Message: _xfdashboard_application_tracker_on_window_opened: Could not resolve window 'xfce4-panel' to any desktop ID
alex@vaioalex:~$ 
```
![snapshot](https://cloud.githubusercontent.com/assets/2082536/8512993/383fd486-235a-11e5-9f4e-05fca1c34cb1.png)

**Comment by alejandro-perez** [comment]
Seeing icon there might be misleading. I actually have them as favourites :). I just removeed them now for clarity.
![snapshot](https://cloud.githubusercontent.com/assets/2082536/8512996/aa9ee92c-235a-11e5-90c8-3ff03c94ab1a.png)

**Comment by gmc-holle** [comment]
From the logs I see that the following applications had been discovered to be running:

* xfce4-terminal
* chromium
* thunderbird

And this looks good to me. So if you have any of these applications stored as favourites at the quicklaunch (at the left hand side) then it should be marked with icon "emblem-default" (usually a green "ok" mark).

In your previous screenshot I see a "terminal" icon but is it really the "xfce4-terminal" terminal application? If no, then it is ok that it is not marked. If it is then it's a bug :(

Please note that only the icons at the quicklaunch are marked. Not anythink else.

**Comment by alejandro-perez** [comment]
Ok, I think I got it. My favourites (terminal and thunar) have been there for long ago. It seems that, for some reason, the old ones did not work. Now that I re-created them, it works.

note this might happen to others :D

**Comment by gmc-holle** [comment]
Yeah, I think I know why this happened. If your favourites have not changed for a long time (since the application database was introduced) then some favourites were stored in a different way that did not match the recognition algorithm of the newly implemented application tracker. So yes, it will happen to other users and I cannot do anything to prevent it .... at least I don't know how prevent it ;)

But in general it seems to be working .... when Linux is running.

I'll keep this issue open because I know it will not run as well when running a BSD-like system.

**Comment by gmc-holle** [comment]
Fully implemented and releases with version 0.5.1. Also running applications which are not stored as favourite one are displayed in quicklaunch as long as at least one window of this application is available.

Issue closed

**Comment by alejandro-perez** [comment]
That is awesome. I'm loooking forward to test it.

**Comment by alejandro-perez** [comment]
Great job! It would be even more awesome if when I click on an already running app, instead of opening a new instance, it would go to the Virtual Desktop it runs, and bring it foreground (as any other traditional dock does, even GS)

**Comment by gmc-holle** [comment]
I created a new issue #97 for it.
