### ISSUE TITLE
Themeable applications view icon

### ISSUE THREAD

**Issue by lacios** [gmc-holle/xfdashboard#46]
Where can I change those icons?

![1 _022](https://cloud.githubusercontent.com/assets/6975946/4929243/b669da42-654f-11e4-99d8-2ffe51b84bee.png)

By adding the property **view-icon: "view-list-symbolic"** to **XfdashboardApplicationView** key, I can change it, but it only works after toggle to applications view.

![1 _023](https://cloud.githubusercontent.com/assets/6975946/4929244/b684c7d0-654f-11e4-885a-c01d2ce61dff.png)

Thanks in advance.

**Comment by gmc-holle** [comment]
Got an idea but it is not sharing the icon but making it themable via CSS.

The commit message should describe it:

```
This is achieved by adding two items.

The first one is a themable property named "icon" in XfdashboardSearchResultContainer which expects a string with a themed icon name or a filename of the icon to display.

The second one is a CSS class which will be added to XfdashboardSearchResultContainer. The CSS class name is build with a prefix "search-provider-" followed by the search provider's object name (like XfdashboardApplicationsSearchProvider for the applications search provider) - so the complete CSS class name would be ".search-provider-XfdashboardApplicationsSearchProvider" (for use in CSS) in this case.
```

This means - by adding the following code to CSS should change the icon for the application search provider from "home" icon to "delete" icon:

```
XfdashboardSearchView XfdashboardSearchResultContainer.search-provider-XfdashboardApplicationsSearchProvider
{
    icon: gtk-delete;
}
```

Closing issue.
