### ISSUE TITLE
Distorted image of SuperTuxKart

### ISSUE THREAD

**Issue by GreenLunar** [gmc-holle/xfdashboard#64]
When SuperTuxKart (a video game) is running, xfdashboard doesn't display its content properly, unless user is opening xfdashboard immediately after starting SuperTuxKart.

![xfd-stk](https://cloud.githubusercontent.com/assets/2053884/5850897/493ee2a2-a206-11e4-8e94-c1989304e21d.png)

**Comment by gmc-holle** [comment]
This looks totally strange. Did you modify the default theme? I hope so. Otherwise I could not explain why it looks mostly horizontal mirrored :S

xfdashboard heavily relies how Clutter retrieves the images for each window. But maybe we can narrow it down. First of all what window manager are you running? xfwm4? Is the compositor turned on? What graphics card are you using and do you know how much video RAM it has?

I could understand that SuperTuxKart may be distorted as it is an OpenGL game as far as I know. But also the image for "Mixer" is distorted and this is a "simple" 2D GTK+ application and this one should look good.

**Comment by GreenLunar** [comment]
I use xfwm4 version 4.10.1.

It did not occur with any other video game such as AssaultCube. SuperTuxKart does appear properly, only when xfdashboard starts immediately after starting SuperTuxKart.

Sometimes, when the aforementioned problem occurs, other images may be distorted.

I will send information of graphics card

**Comment by gmc-holle** [comment]
As you use an unmodified default theme - the first of all is that the widgets in screenshot should not be mirrored. The quicklaunch should be on the left side and the workspace selector on the right side. Also the view selector which is right of the search text box at your screenshot should be located left of the text box. So something really mess up :( Not only the window images.

Beside of the information about your graphics cards, could you tell me which version of Clutter is installed? Which distribution are you running? And do you have enabled the option "Enable workaround for minimized windows" in the settings?

**Comment by GreenLunar** [comment]
> the widgets in screenshot should not be mirrored.

Everything in RTL (Arabic, Farsi, Hebrew) is reversed.

>which version of Clutter is installed? Which distribution are you running?

clutter-1.14.6
clutter-gtk-1.4.4
Salix OS 14.1

> do you have enabled the option "Enable workaround for minimized windows" in the settings?

No, this is a screenshot of xfdashboard 0.3.5 not 0.3.7.

> graphics cards
```
VGA compatible controller
/0/100/1/0


product: RV630 PRO [Radeon HD 2600 PRO] [1002:9589]
vendor: AMD/ATI [Advanced Micro Devices, Inc.] [1002]
bus info: pci@0000:04:00.0
version: 00
width: 64 bits
clock: 33MHz
capabilities:
	Power Management,
	PCI Express,
	Message Signalled Interrupts,
	vga_controller,
	bus mastering,
	PCI capabilities listing,
	extension ROM
configuration:
	driver: radeon
	latency: 0
resources:
	irq: 42
	memory: d0000000-dfffffff
	memory: cffe0000-cffeffff
	ioport: e000(size=256)
	memory: cffc0000-cffdffff
```

**Comment by gmc-holle** [comment]
Hmm .... I have only one idea left. I know some games which will minimize their window when they loose the focus. Does SuperTuxCart behave also like this?

The tech specs told me that this graphics should have 512MB video RAM. I believe that's fairly enough but - to be honest - I have no idea how much video RAM xfdashboard needs and I think it depends highly on the number of open windows and their sizes.

The main problem is that I rely on Clutter to retrieve the window content and the live updates. If Clutter messes up then I will not be able to fix this.

**Comment by GreenLunar** [comment]
It still occurs, but I think I should not blame xfdashboard, until I am certain.
