### ISSUE TITLE
openSUSE packaging issues

### ISSUE THREAD

**Issue by DAP-DarkneSS** [gmc-holle/xfdashboard#68]
Hello!

There are some distro specific build errors: first of all  GenericName tag has to be provided for desktop files, the second one is insufficient desktop file Category (see https://en.opensuse.org/openSUSE:Packaging_desktop_menu_categories f.e.).
And finally:
[   46s] ... running 02-check-gcc-output
[   46s] ... testing for serious compiler warnings
[   46s]     (using /usr/lib/build/checks-data/check_gcc_output)
[   46s]     (using /var/tmp/build-root/openSUSE_13.2-x86_64/.build.log)
[   46s] 
[   46s] I: A function uses a 'return;' statement, but has actually a value
[   46s]    to return, like an integer ('return 42;') or similar.
[   46s] W: xfdashboard voidreturn viewpad.c:511, 512, 513

Any tips please?

**Comment by gmc-holle** [comment]
Hi,

I'm not a packager so I'm sorry that I cannot give you any tip what to do to resolve distro-specific errors. But if I need to change something to help packaging any patch or advice is welcome.

The compile warnings are known and sadly noticed after the last release. To fix this you should cherry-pick to commits 2a3854804388617f4f934443109ac146153735de and cc938cbc6ab1e177d2ce2eedaa2da9110b9c256d .

**Comment by DAP-DarkneSS** [comment]
Thank you! Desktop-s I've already patched. Let me try that commits ;)

**Comment by gmc-holle** [comment]
You are welcome. Please let me know if it worked :)

**Comment by DAP-DarkneSS** [comment]
It works very nice, thank you!
Should I make a pull request with desktop files changed?

**Comment by gmc-holle** [comment]
I'm happy to hear that it worked that a package for opensuse is available :)

Yes, please, send me the patched desktop file.

Will close this issue now.
