### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by GreenLunar** [gmc-holle/xfdashboard#71]
Please add translations from Transifex.

**Comment by gmc-holle** [comment]
Translation "sr" is already added to this repository. The other languages are not translated that far to be added. They are still below 10%. As the transifex client isn't working on my system I have to transfer them manually. So I ask for understanding that I wait that the translation are more complete before adding and updating them.

**Comment by gmc-holle** [comment]
Ok ... strange, now it works ;) Keeping them up-to-date should now be easier :)

Added missing translations from Transifex.

**Comment by damufo** [comment]
Hello:
I do not know where to comment on this.
Galician translation is now 100% (transifex).
Please update.
Thanks.
