### ISSUE TITLE
Include strings of Categories, Exec, Keywords and MimeType

### ISSUE THREAD

**Issue by GreenLunar** [gmc-holle/xfdashboard#72]
* Include strings of `Categories`, `Exec`, `Keywords` and `MimeType` when searching.

Example file: https://github.com/psi-im/psi/blob/master/psi.desktop
Test strings: Jabber, Chat, Qt

* Always include English `Name` and `Comment`, even when locale is not English.

@gottcode, this issue applies to xfce4-whiskermenu-plugin too.

**Comment by gmc-holle** [comment]
Xfdashboard heavily relies on the garcon library for menu item which are also used for desktop app infos - known as ".desktop" files. So I can only filter them by data garcon provides. That excludes filtering for `Keywords` and `MimeType` entries. Also garcon uses always the best matching translated `Name` and `Comment` if available and has a fallback to the untranslated ones which can be any language (it's the coder's decision).

The `Exec` entry is already looked up by xfdashboard when searching by looking up if the basename of the entry (e.g. the basename for /usr/bin/xfdashboard is just xfdashboard) matches the search criterias.

My opinion is that the search behaviour of xfdashboard should match `xfce4-appfinder`. I think `xfce4-whiskermenu-plugin` behaves the same. So for user experience all these applications should behave nearly the same to avoid confusion. IMHO `Keywords` would be an exception if garcon would provides access to this entry.

To make a long story short: I would add `Keywords` if garcon would support it. Maybe an upcoming version of garcon will provide it, then I could include it.

**Comment by gsantner** [comment]
Is there any update on this / garcon? I was somewhat surprised that Keywords are not supported (they and others definitely should) and not planned. Wanted to a bug report now, but found this.

![bildschirmfoto_2017-06-04_22-18-29](https://cloud.githubusercontent.com/assets/6735650/26765097/0daae434-4975-11e7-963d-f927c6ca1e12.png)

![bildschirmfoto_2017-06-04_22-19-17](https://cloud.githubusercontent.com/assets/6735650/26765102/14f57826-4975-11e7-9942-a2de2fd06664.png)

Heres the bug report for keywords on garcon: <https://bugzilla.xfce.org/show_bug.cgi?id=10683>

**Comment by gmc-holle** [comment]
I haven't seen that garcon would support the `Keywords` keyword in desktop files and provides an accessor functions for it. See https://git.xfce.org/xfce/garcon/tree/garcon/garcon-menu-item.h

I had the idea to use mainly garcon for desktop files and to fill the gaps with my own desktop files parser with could includes keywords not supported by garcon. But that means that each file would be loaded and parsed twice which would be inefficient and I cannot stop depending on garcon.

Maybe you should ask for progress at the bug report you found.

**Comment by gsantner** [comment]
Yeah, yesterday I sent the maintainer an email , the bugtracker seems to be somewhat dead
