### ISSUE TITLE
xfdashboard: symbol lookup error: xfdashboard: undefined symbol: garcon_set_environment_xdg

### ISSUE THREAD

**Issue by elnicolo** [gmc-holle/xfdashboard#74]
Hello, when I try to launch xfdashboard, I get the error in the subject.
xfdashboard: symbol lookup error: xfdashboard: undefined symbol: garcon_set_environment_xdg

When I launch it using 'strace xfdashboard', I get the following error:

poll([{fd=8, events=POLLIN|POLLOUT}], 1, 4294967295) = 1 ([{fd=8, revents=POLLOUT}])
writev(8, [{"\203.\5\0\256\0\0\0\1\0s \0\0\1\0\2\10\0\0\207\1\4\0\0\1\7\0\0\0\7\0"..., 84}, {NULL, 0}, {"", 0}], 3) = 84
poll([{fd=8, events=POLLIN}], 1, 4294967295) = 1 ([{fd=8, revents=POLLIN}])
recvfrom(8, "\1\0]\0\0\0\0\0\37\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 4096, 0, NULL, NULL) = 32
recvfrom(8, 0x1080564, 4096, 0, 0, 0)   = -1 EAGAIN (Resource temporarily unavailable)
recvfrom(8, 0x1080564, 4096, 0, 0, 0)   = -1 EAGAIN (Resource temporarily unavailable)
open("/usr/share/locale-langpack/en_US.utf8/LC_MESSAGES/glib20.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US.utf8/LC_MESSAGES/glib20.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-bundle/en_US.utf8/LC_MESSAGES/glib20.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_US/LC_MESSAGES/glib20.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US/LC_MESSAGES/glib20.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-bundle/en_US/LC_MESSAGES/glib20.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en.utf8/LC_MESSAGES/glib20.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.utf8/LC_MESSAGES/glib20.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-bundle/en.utf8/LC_MESSAGES/glib20.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en/LC_MESSAGES/glib20.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/glib20.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-bundle/en/LC_MESSAGES/glib20.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
getcwd("/home/flucas", 4096)            = 13
writev(2, [{"xfdashboard", 11}, {": ", 2}, {"symbol lookup error", 19}, {": ", 2}, {"xfdashboard", 11}, {": ", 2}, {"undefined symbol: garcon_set_env"..., 44}, {"", 0}, {"", 0}, {"\n", 1}], 10xfdashboard: symbol lookup error: xfdashboard: undefined symbol: garcon_set_environment_xdg
) = 92
exit_group(127)                         = ?
+++ exited with 127 +++

Someone can help me?

**Comment by gmc-holle** [comment]
Hi  elnicolo,

looks like your are compiling xfdashboard again garcon at version 0.3.0 or higher but the final executable file is linked against or will load garcon version 0.2.0.

Please check which libgarcon file will be loaded when launching xfdashboard. You could use the following command:

```
ldd /path/to/xfdashboard | grep libgarcon
```

You should get something similar to this:

```
$ ldd /usr/bin/xfdashboard | grep libgarcon
	libgarcon-1.so.0 => /usr/lib64/libgarcon-1.so.0 (0x00007fc3e6d5e000)
```

Is the path resolved for libgarcon really the path you expect?

**Comment by gmc-holle** [comment]
Could you solve your problem?

**Comment by elnicolo** [comment]
Hello I could solve the problem installing other version of libgarcon:
rpm -qa | grep libgarcon
libgarcon-1-0-0.4.0-46.6.x86_64
libgarcon-data-0.2.1-2.1.3.noarch
libgarcon-branding-openSUSE-4.10.0-20.1.1.noarch
libgarcon-lang-0.2.1-2.1.3.noarch

rpm -qa xfdashboard
xfdashboard-0.3.91-1.1.x86_64

But when I launch xfdashboard and first time I click anywhere on the screen, it crashes...
This is the "strace xfdashboard" tail:

ll([{fd=10, events=POLLIN}], 1, 4294967295) = 1 ([{fd=10, revents=POLLIN}])
recvfrom(10, "\1\1\23\2\0\0\0\0\306\0\340\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 4096, 0, NULL, NULL) = 32
recvfrom(10, 0x189a474, 4096, 0, 0, 0)  = -1 EAGAIN (Resource temporarily unavailable)
recvfrom(10, 0x189a474, 4096, 0, 0, 0)  = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=10, events=POLLIN|POLLOUT}], 1, 4294967295) = 1 ([{fd=10, revents=POLLOUT}])
writev(10, [{"6\2\2\0\f\0\240\6\216\3\3\0Z\6`\1\0\0\0\0+\0\1\0", 24}, {NULL, 0}, {"", 0}], 3) = 24
poll([{fd=10, events=POLLIN}], 1, 4294967295) = 1 ([{fd=10, revents=POLLIN}])
recvfrom(10, "\1\1\26\2\0\0\0\0\306\0\340\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 4096, 0, NULL, NULL) = 32
recvfrom(10, 0x189a474, 4096, 0, 0, 0)  = -1 EAGAIN (Resource temporarily unavailable)
recvfrom(10, 0x189a474, 4096, 0, 0, 0)  = -1 EAGAIN (Resource temporarily unavailable)
write(3, "\1\0\0\0\0\0\0\0", 8)         = 8
inotify_rm_watch(13, 14)                = 0
futex(0x2d21460, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x2d21460, FUTEX_WAIT_PRIVATE, 2, NULL) = 0
inotify_rm_watch(13, 13)                = 0
futex(0x2d21460, FUTEX_WAKE_PRIVATE, 1) = 1
inotify_rm_watch(13, 12)                = 0
futex(0x2d21460, FUTEX_WAKE_PRIVATE, 1) = 1
inotify_rm_watch(13, 11)                = 0
futex(0x2d21460, FUTEX_WAKE_PRIVATE, 1) = 1
inotify_rm_watch(13, 10)                = 0
futex(0x2d21460, FUTEX_WAKE_PRIVATE, 1) = 1
inotify_rm_watch(13, 9)                 = 0
futex(0x2d21460, FUTEX_WAKE_PRIVATE, 1) = 1
inotify_rm_watch(13, 8)                 = 0
futex(0x2d21460, FUTEX_WAKE_PRIVATE, 1) = 1
inotify_rm_watch(13, 7)                 = 0
futex(0x2d21460, FUTEX_WAKE_PRIVATE, 1) = 1
inotify_rm_watch(13, 6)                 = 0
futex(0x2d21460, FUTEX_WAKE_PRIVATE, 1) = 1
inotify_rm_watch(13, 5)                 = 0
futex(0x2d21460, FUTEX_WAKE_PRIVATE, 1) = 1
inotify_rm_watch(13, 4)                 = 0
futex(0x2d21460, FUTEX_WAKE_PRIVATE, 1) = 1
inotify_rm_watch(13, 3)                 = 0
futex(0x2d21460, FUTEX_WAKE_PRIVATE, 1) = 1
inotify_rm_watch(13, 2)                 = 0
futex(0x2d21460, FUTEX_WAKE_PRIVATE, 1) = 1
inotify_rm_watch(13, 1)                 = 0
futex(0x2d21460, FUTEX_WAKE_PRIVATE, 1) = 1
sendmsg(12, {msg_name(0)=NULL, msg_iov(2)=[{"l\1\1\1_\0\0\0\17\0\0\0\177\0\0\0\1\1o\0\25\0\0\0/org/fre"..., 144}, {"Z\0\0\0type='signal',sender='org.xf"..., 95}], msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 239
sendmsg(12, {msg_name(0)=NULL, msg_iov(2)=[{"l\1\1\1\237\0\0\0\20\0\0\0\177\0\0\0\1\1o\0\25\0\0\0/org/fre"..., 144}, {"\232\0\0\0type='signal',sender='org.fr"..., 159}], msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 303
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
futex(0x17484b0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x1747c60, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x173c2d0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7f478b529620, FUTEX_WAKE_PRIVATE, 1) = 0
exit_group(0)                           = ?
+++ exited with 0 +++

**Comment by gmc-holle** [comment]
Sorry. But I cannot see the source of problem at the strace log. Could you start xfdashboard in a debugger like gdb and send the backtrace in this issue? The following command in a terminal should do it if you are **not** running xfdashboard in daemon mode:

```
gdb /usr/bin/xfdashboard
```

The requested backtrace can be listed from the moment on when xfdashboard crashed:

```
thread apply all bt full
```

**Comment by gmc-holle** [comment]
In the meantime version 0.4.0 was released. Although I don't anything has changed for you I ask you to give it a try. If it still crashes could you please provide the backtrace as describe above?

**Comment by gmc-holle** [comment]
No reaction. So I feel free to close this bug report.
