### ISSUE TITLE
voidreturn: A function uses a 'return;' statement, but has actually a value to return

### ISSUE THREAD

**Issue by DAP-DarkneSS** [gmc-holle/xfdashboard#75]
[  263s] I: A function uses a 'return;' statement, but has actually a value
[  263s]    to return, like an integer ('return 42;') or similar.
[  263s] W: xfdashboard voidreturn search-result-set.c:173, 174
[  263s] W: xfdashboard voidreturn search-view.c:684

PS 0.3.91

**Comment by gmc-holle** [comment]
Indeed you're right. Thanks. :)  Fixed with commit 803241c4e9673e4fe74b203e553aa9b974e26efe
