### ISSUE TITLE
Problem autostarting xfdashboard in xubuntu 14.04 (maybe a general problem?)

### ISSUE THREAD

**Issue by ivan-luk** [gmc-holle/xfdashboard#76]
Hello
I couldn't  autostart xfdashboard in xfce 4.12 in ubuntu 14.04, flagging the proper entry in "Session and Startup". I solved editing  /etc/xdg/xfdashboard-autostart.desktop, changing the entry "TryExec=/usr/bin/xfdashboard -d" 
to 
"TryExec=/usr/bin/xfdashboard"
From a short overview of http://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables, it seems to me that TryExec keys must not contain flags but only the name of the executable file.
Regards,
Ivan

**Comment by gmc-holle** [comment]
Thanks for reporting this issue. I agree. The spec are only talking about the path to the executable in "TryExec" and about path and arguments in "Exec". So I removed any argument in "TryExec" with commit 960dff6a33ba4f17f5df8d9159b341bd8aaf0415.

Closing issue.
