### ISSUE TITLE
Can't select windows or change desktop with mouse, only with keyboard

### ISSUE THREAD

**Issue by ivan-luk** [gmc-holle/xfdashboard#77]
Hello, again a problem with xfdashboard 0.3.91 in xubuntu 14.04 with xfce 4.12. 
Since I have just begun using xfdashboard, can't say if it's a new issue.
When I start xfdashboard,  using the mouse, just one or two windows are selectable and I can't change desktop. If I click on the favorites bar or in the search bar, or if I start an application in the applications view, it works ok. All is ok using the keyboard.
I have tried to log in as a new user, with the same results.
Regards
Ivan

**Comment by gmc-holle** [comment]
Hi,

it sounds very similar to the very first issue ( #1 ) reported but it's one year ago. It was solved and I never heard of it again. Therefore I have some questions ;)

Which windows can be clicked and selected by mouse successfully? Are these only the windows in the first row or only the first two windows in the first two columns? Can you change the active workspace by moving the mouse pointer over the workspace selector at the right side and using the mouse wheel? Can you click any other workspace at the workspace selector and the active workspace changes? If it works, does it work with all workspaces? Can you start all application by clicking their icon in the quicklaunch (the favourites bar) at the left side?

And last but not least: Which version of Clutter is installed?

Sorry for having so many questions.

**Comment by ivan-luk** [comment]
Hello
no problem for your questions: I am glad to help as I can, since I like your program.
-- Which version of Clutter is installed?
I have a standard xubuntu 14.04 amd64 just updated. Regarding clutter I have 2 packages installed:
libclutter-1.0-0 version 1.16.4-0ubuntu2
libclutter-gtk-1.0-0 version 1.4.4-3ubuntu2.2
--Which windows can be clicked and selected by mouse successfully? Are these only the windows in the first row or only the first two windows in the first two columns? 
It depends:
1. With up to 4 open windows, any window I click on, everytime the first window is selected;
2. With more than 4 open windows, 
          - if I click on the first 2 windows on the first column, the correct window is selected
          - if I click on the 3rd window on the first column, the 2nd is selected
          - if I click on any other window, nothing happens
3. With up to 4 open windows just after that I have closed one of the windows
        - if I click on one of the 2 windows in the first row, the 1st is selected
        - if I click on the window(s) on the 2nd row, nothing happens
-- Can you change the active workspace by moving the mouse pointer over the workspace selector at the right side and using the mouse wheel? 
No
-- Can you click any other workspace at the workspace selector and the active workspace changes?
No
-- Can you start all application by clicking their icon in the quicklaunch (the favourites bar) at the left side?
Yes

Ivan

**Comment by gmc-holle** [comment]
Just a shot into the dark: I recognized a problem when two monitors were connected but "libxinerama" was not installed or not enabled when compiling xfdashboard that every object in the right half of the application's window were not selectable (like the right half of the windows view and anything in workspace selector) and an object in left half was selected instead.

* So do you have two or more monitors connected to your workstation?
* Did you compile xfdashboard by your own and was libxinerama installed and enabled when you compiled it?
* Or did you install xfdashboard via a package? If so, which one?

**Comment by ivan-luk** [comment]
Hi
I've got just 1 monitor.
First I installed http://ppa.launchpad.net/xubuntu-dev/extras/ubuntu/pool/main/x/xfdashboard/xfdashboard_0.3.91-0ubuntu1~14.04_amd64.deb
from the Xubuntu Extras ppa, then I rebuilt the package from the same source with xinerama enabled: both packages have the same issues.
Should I try rebuilding without xinerama ?

**Comment by gmc-holle** [comment]
If you could rebuild without xinerama and testing it if it had the same issues, it could help narrowing down the source. Thanks.

**Comment by ivan-luk** [comment]
Can you please tell me how to to rebuild an ubuntu package without xinerama?
It's been a very long time since I last messed with source files ...
I have tried adding "--disable-xinerama" to the dh_auto_configure line in the debian/rules file, but the resulting xfdashboard  still depends on xinerama...

**Comment by gmc-holle** [comment]
Sorry, I do not use any distributed based on binary packages. I use Gentoo which compiles every package on its own.

But adding "--disable-xinerama" to the configure script should be enough - at least I tried it with this argument and is did not depend on Xinerama anymore.

**Comment by ivan-luk** [comment]
Yes, that's true, but I wanted to build a package so that every file was put in the right place ...
when  I run
./configure --disable-xinerama
the final part of the output is:
Features enabled:
  XComposite:  yes
  XDamage:     yes
  Xinerama:    no

Then I run make, and the output of 
ldd xfdashboard/xfdashboard|grep rama
is
libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007fa3c99ad000)

So the executable still depends on xinerama ...  what am I doing wrong ???

**Comment by gmc-holle** [comment]
I did the same and xfdashboard did not depends on libXinerama anymore. I'm sorry but at the moment I do not know what went wrong :(

In the meantime I think I found a way to discover if the coordinates of your pointer device (the mouse ;) ) is translated successfully which is needed for selecting the right object successfully. But you need to copy and modify the default theme to check it:

* Copy the default theme, usually located at /usr/share/themes/xfdashboard to ~/.themes or ~/.local/share/themes where ~ is the path to your home directory, e.g.
```
cp -a /usr/share/themes/xfdashboard ~/.themes/

-or-

cp -a /usr/share/themes/xfdashboard  ~/.local/share/themes/

```
* Add the following lines at the end of xfdashboard.css under ~/.themes/xfdashboard/xfdashboard-1.0/xfdashboard.css or  ~/.local/share/themes/xfdashboard/xfdashboard-1.0/xfdashboard.css
```
XfdashboardActor:hover
{
        background-type: outline;
        outline-color: #ff0000ff;
        outline-width: 8.0;
}
```
* Launch xfdashboard in *non-daemon* mode
* Now most of the objects on the screen should get a big red border if the mouse enters them. Not all but most of them - but especially the window and workspace objects shoud get a big red border as soon as the mouse pointers enters them. Does this happen to you also? Or does some window or workspace object do not get the big red border?

Here is a example how a windows object should look like if the mouse is over it:

![](http://xfdashboard.froevel.de/big-red-border-window-object.png)

**Comment by ivan-luk** [comment]
Well, with 3 windows , only the first window has a red border, independently from the mouse position...
![istantanea_2015-04-11_01-02-36](https://cloud.githubusercontent.com/assets/11861611/7098853/4c72ef58-dfe7-11e4-8314-d73ea02d5b35.png)

**Comment by gmc-holle** [comment]
Strage :( Ok, please give me a night to think about it. It is very strange to me and at the moment I don't have any clue

**Comment by ivan-luk** [comment]
Ok, tomorrow I'll download directly your source package and build it : let's see if anything changes...

**Comment by gmc-holle** [comment]
I tried two other versions of Clutter but one is too old and didn't work at all. The other one had no problems so I could not reproduce the problem.

The "xinerama" problem I mentioned only happened when at least two monitors were connected. So I don't think that the Xinerama extension is the source of this problem.

Could you reproduce the problem when compiling xfdashboard from the sources?

**Comment by gmc-holle** [comment]
Any progress?

**Comment by ivan-luk** [comment]
Hello,
of course you missed the last line from my last post, which I edited after a few hours... Nevermind, I repeat what I said, that the problem was the same even compiling from your sources with xinerama disabled.... In the last weekend, after maybe 5 years a gave KDE a try and so I installed kubuntu 14.04.2 LTS: so for now I don't have XFCE any more... 
I did really appreciate your commitment very much, and so I'm really sorry that I can be of no help for now ... 
BTW, for what it count, I have just installed xfdashboard 0.4.0 from the same repository ppa:xubuntu-dev/extras and the problem is still the same ... Maybe the problem is specific to my hardware or to *ubuntu. 
I think that if no one else confirm this bug you can close it for now...
Thank you for your caring.
Ivan

**Comment by gmc-holle** [comment]
Thanks for your feedback and I'm sorry I really missed the part of your last post. I haven't heard of others having the problem but it doesn't mean it may not exist. I follow your suggestion and close this issue for now.

**Comment by ytzml** [comment]
Hi guys, it seems to me that I have exactly the same issue as the one described above. I can use the mouse to click on only one or two windows. I cannot click on workspaces to change them. Still everything works if I use keyboard. If there is a fix for that, please let me know. If not, I'm eager to help you hunt down this bug.

**Comment by gmc-holle** [comment]
Hi,

what version of xfdashboard and what version of Clutter do you have installed?

Regards,
Stephan

**Comment by ytzml** [comment]
My xfdashboard version is 0.5.0-0ubuntu1~14.04
As for Clutter, I understand that we are talking about libclutter 
package, right? If so, that is  1.16.4-0ubuntu2.

Cheers,
Jacek



W dniu 25.11.2015 o 10:57, gmc-holle pisze:

**Comment by gmc-holle** [comment]
It's a known issue when Clutter (libclutter) prior to version 1.18 is installed. You will see lots of different problem like "dragging to workspace" as described in #95 

But it can be solved easily :) You upgrade libclutter to version 1.18 or higher. Or downgrade xfdashboard to version 0.4.2 (latest stable version) or upgrade to at least 0.5.2 (development version). Or both ;)

**Comment by ytzml** [comment]
OK, thank you for your help.

All the best,
Jacek

W dniu 25.11.2015 o 13:01, gmc-holle pisze:
