### ISSUE TITLE
Allow moving windows from one desktop to another from the side panel

### ISSUE THREAD

**Issue by alejandro-perez** [gmc-holle/xfdashboard#79]
Sometimes I just want to move a window (e.g from desktop 4 to desktop 1) when I'm at desktop 1.

It would be nice to allow to move the thumbnail from the side panel, in a similar way I can do it with XFCE's panel applet.

**Comment by gmc-holle** [comment]
I like this idea so mark this issue as an enhancement for 0.6.0. I cannot promise that I'll manage to get it working but I will try ;)

**Comment by alejandro-perez** [comment]
I have an additional idea on this. I won't create a new issue as I think it shares a lot of code with this one.

When I click on the side panel, it would be interesting to give focus to the clicked window. Ej., imagine I have two web browsers on desktop 3, one with digg and the other with piratebay. I'm currently on desktop 4, and I'd like to look for a *CC* movie, so I go to overview and click on top of the piratebay browser. Currently, it just goes to desktop 3, and the focus is where it was the last time I was there.

Since I guess this would be related to add events to the side panel (drag, click, etc), I leave it related to this issue.

**Comment by alejandro-perez** [comment]
Whenever you think I'm spamming, just tell me. Otherwise I will write here all the ideas and wishes I have :)

**Comment by gmc-holle** [comment]
Don't mind :) I'm not used so much response, bugs and ideas and I don't know where to start ;) ... but keep going on.

In the meantime I managed to get the windows in the workspace draggable (dropping still fails) but the workspaces themselves are not clickable anymore. It seems to a bug in capturing mouse/pointer events. I will keep trying.

**Comment by alejandro-perez** [comment]
Don't hesitate to discard any of them, just trying to help, not the opposite :)

It's great you managed to do that. I'm almost a daily user of xfdashboard. Only two things prevent me of using it more often. One is this one, and the other is the CPU associated to the movement of windows.

**Comment by gmc-holle** [comment]
I'm ashamed that it lasted so long to implement this feature and in the end it was so easy. You can now drag and drop any window from windows view or workspace (at the right side panel by default) to any windows view or workspace.

It is now be implemented and I'm closing this issue. Sorry for the very long delay.

**Comment by alejandro-perez** [comment]
Oh, that's fantastic! Thanks!
You don't have to be sorry, you've have done a wonderful thing here and every feature you implement is a gift. I do have my own personal projects and know how hard it is.

Again, thanks!
