### ISSUE TITLE
Xfdashboard shows windows in the background instead of showing wallpaper

### ISSUE THREAD

**Issue by alejandro-perez** [gmc-holle/xfdashboard#80]
And my .themes or .local/share/themes folders are empty.

**Comment by gmc-holle** [comment]
It seems that the background window pixmap could not be found. To be sure - could you please run the following command in a terminal and after xfdashboard has started quit it after some second without doing anything? Please ensure that xfdashboard is running standalong (not in daemon mode).

----
G_MESSAGES_DEBUG=xfdashboard xfdashboard | egrep "[dD]esktop window( ID)?"
----

Please attach the output in the terminal to this issue.

**Comment by alejandro-perez** [comment]
Hi, sure. Here you are:

    alex@vaioalex:~$ G_MESSAGES_DEBUG=xfdashboard xfdashboard | egrep "[dD]esktop window( ID)?"
    (xfdashboard:28731): xfdashboard-DEBUG: Desktop window was not found - maybe it was not created or signalled yet
    (xfdashboard:28731): xfdashboard-DEBUG: Found desktop window with signal 'window-opened', so disconnecting signal handler

But, please, note that the problem *only* occurs when deamon mode is active. Otherwise it works well.

**Comment by gmc-holle** [comment]
Oh Sorry. I have missed this piece of information. I must have read you previous issue not carefully :(

But the test for daemon mode is nearly the same. As previously ensure that no another instance of xfdashboard is running (in daemon mode) then run the following command in a terminal. It's the same command but this time the parameter "-d" is added for daemon mode.

```
G_MESSAGES_DEBUG=xfdashboard xfdashboard -d | egrep "[dD]esktop window( ID)?"
```

Then call xfdashboard as usually via keyboard shortcut, panel launcher or via the menu. After xfdashboard has started, wait some seconds and quit xfdashboard. To stop the daemon instance in the terminal press either <Ctrl>+C in that window or open another terminal and execute: 

```
xfdashboard -q
```

**Comment by alejandro-perez** [comment]
(xfdashboard:1810): xfdashboard-DEBUG: Could not get window instance for desktop window ID
(xfdashboard:1810): xfdashboard-DEBUG: Could not get window instance for desktop window ID

**Comment by gmc-holle** [comment]
Thanks. In the meantime I could reproduce the problem and I think I localized the source of this problem.

I don't know why but in daemon mode I get a different window ID for the background image than running standalone. I have tried a workaround and it worked. I will clean up the code now and commit this workaround later this day.

**Comment by gmc-holle** [comment]
I was quicker than expected. Committed workaround with commit 62d87094630d157ca4e5b195de1f88380589d62d

If possible please check if it solves this issue at your system.

**Comment by alejandro-perez** [comment]
Hi!

It does solve the problem, thanks!

**Comment by gmc-holle** [comment]
Great :D
Closing issue

Thanks for your help to solve this problem

**Comment by alejandro-perez** [comment]
Is this bug still present in 0.4.1? I just downloaded this version (instead of getting the head of the repository) and I got surprised to see this bug present. Does it makes any sense or did I make a mistake?

**Comment by gmc-holle** [comment]
I just did not remember this fix when I built the new release. But I needed to built a new release quickly and I included it now. So please look for version 0.4.2
