### ISSUE TITLE
Change background of right side panel

### ISSUE THREAD

**Issue by alejandro-perez** [gmc-holle/xfdashboard#81]
Hi,

I wanted as usual to propose a small improvement. The panel on the right side (the one with the small workspace) has a black background. Not sure whether you can change that by theming. 

In any case, would it be possible to use the same greyed out wallpaper as in the main window? That's something GS does.

**Comment by gmc-holle** [comment]
No, that's not possible in it's current implementation. You could only change a background color of the "small workspaces".

Although I mark this issue as enhancement for now I will think about if and how to implement this request.

**Comment by alejandro-perez** [comment]
But... is it possible to change it by "theming"? The problem is that my terminals become almost irreconocible, since they are mostly black :)

**Comment by gmc-holle** [comment]
The "small workspaces" are of type XfdashboardLiveWorkspace which are derived from XfdashboardBackground. So this actors inherits all properties of both of them but only the properties of XfdashboardBackground are themable currently. See http://xfdashboard.froevel.de/theming.html#theme-stylable-properties-XfdashboardBackground for more information about theming actors derived from XfdashboardBackground.

**Comment by alejandro-perez** [comment]
Thanks. I will look at it.

**Comment by gmc-holle** [comment]
I don't know my code anymore :P

By the way the "big" workspace selector of type XfdashboardWorkspaceSelector is also derived from XfdashboardBackground and inherits the same properties from it like XfdashboardLiveWorkspace (used by the "small" workspaces).

At the end you should be able to theme it without having me change anything at the code.

**Comment by alejandro-perez** [comment]
So, I will be able to make the small workspaces to show the actual wallpaper instead of solid black color?

**Comment by gmc-holle** [comment]
No, it will just help you to get rid of the background colors - making them transparent instead of solid black color which makes your terminal windows hard to see. Making them transparent should increase visibility.

Showing a minized wallpaper will still require a change of code so I'll this bug open.

**Comment by alejandro-perez** [comment]
I see. Transparent should be good enough by now.

**Comment by gmc-holle** [comment]
With commit 1959f14afb129afa00206e1caeb7bf2059f3f104 the background of the "small" workspaces can now the desktop's wallpaper like the stage does. Because it is enabled by default at the stage it is also enabled by default at the "small" workspaces as they share the same content and no additional texture creation is needed.

Closing bug.

**Comment by alejandro-perez** [comment]
Tested! And, for me, it is completely amazing! Great work!

**Comment by alejandro-perez** [comment]
Does not work with     show-window-content: false;

**Comment by gmc-holle** [comment]
It works for me :/

I changed xfdashboard.css to

```
/* Live workspaces */
XfdashboardLiveWorkspace
{
	background-type: outline;
	background-image-type: desktop;
	outline-color: #404040ff;
	outline-width: 1.0;
	show-window-content: false;
}

XfdashboardLiveWorkspace:active
{
	background-type: outline;
	outline-color: #ffff00ff;
	outline-width: 2.0;
	show-window-content: true;
}
```

**Comment by alejandro-perez** [comment]
I does work for me too! I was missing  background-image-type: desktop;

Thanks!
