### ISSUE TITLE
(Suggestion) Improve search responsivenes 

### ISSUE THREAD

**Issue by alejandro-perez** [gmc-holle/xfdashboard#86]
Let me share with you my experience with desktop searchs, and how I improved the responsivenes of the results.

You may have observed that when you, for instance, type "analyze", it actually performs 7 searchs, being the most heavy the first one, which needs to return all the results containing "a". But actually, noone usually cares about the results of "a", or even "an". I have solved this issue by using different techniques, all of them valid.

1) Avoid searching with one (or even two) characters. Searchs will start when the user have introduced enough information. This is something that the autocomplete plugin of jquery does.
PROS: Very very simple to implement. Avods the heaviest search.
CONS: Still heavy on two, three, four.. characters. Sometimes you *may* want those results.

2) Do no start searching after an amount of time have passed after the last character introduced by the user. Usually 0.2s is a good value. Usually, you write "anali" very fast, with less than 0.1s between characters. So, whenever you write fast enough, only the last search will be performed.
PROS: Might avoid all superfluous searchs. No need of complex threading mechanisms, just timers (ej. on_click -> new_timer(do_serach, 0.2))
CONS: Searchs are asynchronous (don't know whether they are currenctly). Results are not provided inmediately.

3) Do searches in an independent thread/process, and allow cancellation. 
PROS: The best approach. Provides inmmediate results.
CONS: Requires dealing with asynchronous searches and, probably cancellation points. You need to introduce a cancel_search on each search provider.
 
Approaches 2 and 3 can live together as long as your search manager allows asyncrhronous searrches. You can look at my design here (https://bitbucket.org/aperezmendez/pyneedle), but basically my manager does two things:
a) As soon as it receives an entry from the user, it calls "provider.do_search(terms)". 
b) The manager provides a callback to allow providers to introduce the results.

In this way, it is up to the provider impleemntation of "do_search" to create a new thread, or a new process, or a timer, or just do the search and provide the results (as it is currently).

Hope this helps!

**Comment by alejandro-perez** [comment]
More information on this. 

Since you are using glib, you can make direct use of g_timeout_add (). That should be quite easy and requrie no major changes on your code, nor worrying about threads.

Let's say your manager do searchs by calling to engine.do_search(terms). Instead of doing that, whenveer you receive a new keystroke, you cancel the timer and create a new one for 0.3s in the future. Let me use pseudocode:

```
manager_perform_search(terms)
{
     g_source_remove(timer);
     timer = g_timeout_add(0.3, engine.search(terms));
}
```

**Comment by alejandro-perez** [comment]
Hi, it works like a charm (I implemented it using really bad and fast programming). If you are interested, I can send you a diff with the code. Sure you can improve it.

**Comment by alejandro-perez** [comment]
Here you are. This is nasty and bad. You probably can do with one function less, using less pointers, etc. You might need to assure timer is deleted when app is suspended/closed. But as it is you can compile and test the responsiveness it gives using 100ms of delay.

Hope you like it :)
https://gist.github.com/d8059edfbe255d80d5b9.git

**Comment by gmc-holle** [comment]
I dont' see the difference between both GISTs but their are pretty near my first idea on how to implement your suggestion at 2.)

But let me a go back a step and tell you my ideas. ;)

Regarding 1.) I don't think that a search should not be starting because only one or two characters are entered. The user might be confused if nothing happens (expect for blanking the view, e.g.) when he entered "F" to start his search for "firefox" and anything else what contains an "F". An he get more confused if suddenly the search view fills when he entered "I" and "R" later on.

Regarding 2.) I agree fully. This was also - more or less - my first ideas when I read the topic of this bug and it is the easiest solution to implement as you already showed at your patches. I think I will implement this.

Regarding 3.) This is the solution I want and I have a theoretical prototype for it but no implementation of it. But the goal is to call each search provider asynchronously in a seperate thread. As xfdashboard already relies on the library exo I think I will try to make use of ExoSimpleJob because it seems to easier to use than GAsyncResult etc of Glib. I cannot make use of GTask because I would have to raise the minimum version of Glib.

**Comment by gmc-holle** [comment]
Note to myself: Flagged issue as enhancement for version 0.6 but only for implementing a delay for the initial search.

**Comment by alejandro-perez** [comment]
El 03/05/15 a las 10:17, gmc-holle escribió:
>
> I dont' see the difference between both GISTs but their are pretty 
> near my first idea on how to implement your suggestion at 2.)
>

That's because they are identical, but I couldn't see the first one :)

> But let me a go back a step and tell you my ideas. ;)
>
> Regarding 1.) I don't think that a search should not be starting 
> because only one or two characters are entered. The user might be 
> confused if nothing happens (expect for blanking the view, e.g.) when 
> he entered "F" to start his search for "firefox" and anything else 
> what contains an "F". An he get more confused if suddenly the search 
> view fills when he entered "I" and "R" later on.
>

I see your point. But this is quite usual in many searches. Although I 
agree that might not make sense in desktop searches.

> Regarding 2.) I agree fully. This was also - more or less - my first 
> ideas when I read the topic of this bug and it is the easiest solution 
> to implement as you already showed at your patches. I think I will 
> implement this.
>

Great!

> Regarding 3.) This is the solution I want and I have a theoretical 
> prototype for it but no implementation of it. But the goal is to call 
> each search provider asynchronously in a seperate thread. As 
> xfdashboard already relies on the library exo I think I will try to 
> make use of ExoSimpleJob because it seems to easier to use than 
> GAsyncResult etc of Glib. I cannot make use of GTask because I would 
> have to raise the minimum version of Glib.
>
I think this would be the best option (this is the one I chose for my 
pyneedle app, although I used processes). This provides immediate 
results, and since jobs/processes can be cancelled, they do not 
interfere with responsiveness.

In any case, I think I will probably make a couple of simple search 
engines, one for vinagre's bookmarks, one for desktop bookmarks, and the 
last one for disks. They should not be difficult, and will let me get 
rid of my beloved "kupfer".

I will try to follow the proper path now, cloning the repository, and 
making a pull request afterwards.

Regards

**Comment by alejandro-perez** [comment]
It seems search-engines are way more complex right now than I expected, and the current one for apps is probably specially complex. I know this is asking too much, but a sample engine would be great :)

**Comment by gmc-holle** [comment]
I can try to create a fully documented skeleton for a XfdashboardSearchProvider derived object. But it takes some time as I'm currently very busy at work. I hope to finish it this weekend. I ask for your patience.

**Comment by alejandro-perez** [comment]
That'd be great, no need to rush it. That's for perfection!

What I have seen is that you have the provider on one side, the button on the other... It might be complicated creating a simple provider, as there are several things to do. It might be worth having some kind of simpleprovider object, that only needs to fill a few information (e.g. provide a list of [icon, title, descripcion, click action callback]). That could be called SimpeSearchProvider, and we could inherit from it. But as you said, this is on the long term, I'm pretty busy as well.

**Comment by gmc-holle** [comment]
Implemented delay for the initial search with configurable initial timeout interval (xfconf and settings dialog) - commit e05166b18f27ada193baa2430d9818ec20a16cc8 and f5796e58ff4fe9bcb24cf8785a0527178dc3c93f

Closing issue
