### ISSUE TITLE
(Improvement) Add a second side panel on multimonitor modes

### ISSUE THREAD

**Issue by alejandro-perez** [gmc-holle/xfdashboard#87]
Hi,

at work I have two monitors. When I go to "overview" mode, I have a extra-large side panel reprsenting both monitors. Would it be possible to include one side panel per montior?

Attached you can find how it looks like:
![captura de pantalla_2015-04-27_08-37-26](https://cloud.githubusercontent.com/assets/2082536/7342734/ae1a80ee-ecb8-11e4-9e7c-e3c75cb0a7c0.png)

I would like it to look somehow like this:
![gnome-shell](https://extensions.gnome.org/static/extension-data/screenshots/screenshot_323_1.png)

**Comment by gmc-holle** [comment]
Adding a workspace selector even to non-primary monitors can be done already by a theme. But I need to add a themable option to limit the windows shown in the workspace selector on each monitor to the size of this monitor and the windows shown at this monitor (like I did for the windows view).

**Comment by alejandro-perez** [comment]
I'd love to see this. Otherwise the side bar "eats" all my space :)

**Comment by gmc-holle** [comment]
First I corrected the calculation of the size of the workspace selector in commit b941f20f271011b17ad29a572b1e75ae73132af8.

It used the total size of all monitors in its calculation instead of the size of the monitor where it shown at. Therefore it was getting too big.

Next I'll try to add a themable option to only show the windows of the monitor where this workspace selector is shown at.

**Comment by gmc-holle** [comment]
Implmented themable option to only show the windows of the monitor where this workspace selector is shown at and changed themes to use new option with commit 46346a7b4f880076e0776b3a172a31d46a115c1c

Closing issue.

**Comment by alejandro-perez** [comment]
Great! Thanks!
I cannot wait to see it working on Monday at work!

**Comment by alejandro-perez** [comment]
It works great! Thanks!

**Comment by gmc-holle** [comment]
Great. Thanks for feedback :)
