### ISSUE TITLE
Windows wrongly managed when desktops change dynamically

### ISSUE THREAD

**Issue by alejandro-perez** [gmc-holle/xfdashboard#91]
This is a very low priority stuff. Just leave it there for when you have nothing else to do.

When a desktop is dynamically deleted, all the windows on that deskotp are moved to the new last one. This seems not to be handled by xfdashboard, which show the windows in the small desktops, but not in the big desktop. This only happens when you delete the desktop while in overview mode (before delenting it).

**Comment by gmc-holle** [comment]
Then xfdashboard does not get the signal 'workspace-changed' from libwnck for these windows and it relies on that signal. So I need another workaround :(

**Comment by alejandro-perez** [comment]
That's an extremely rare case that does not need to be solved by know. 
The windows are represented correctly on the small workspaces, though, 
it is just the big workspace the one that don't notice.

**Comment by gmc-holle** [comment]
Then it's a bug if the "small" workspace do it right but the windows view not.

**Comment by alejandro-perez** [comment]
If you have XFCE (I guess you do), just assign a keybinding to "delete 
the last workspace" action in the window manager. I have the Ctrl+Alt+-, 
but use whatever you want. Then.

1. Go to the last workspace.
2. Assure you have an open window there (you can open it now if you need 
it).
3. Go to overview mode
4. Use the keybinding to delete this last workspace.
5. You got it. The small workspace should show the windows properly, but 
the windows view not.

Regards

**Comment by gmc-holle** [comment]
Should also be fixed now with commit 9c527f22b9c12fc7875efb64d6dedbf03f4e17d7

**Comment by alejandro-perez** [comment]
It certainly seems it does. THanks!

**Comment by gmc-holle** [comment]
Great :) Bug closed.
