### ISSUE TITLE
Notifications and xfdashboard

### ISSUE THREAD

**Issue by alejandro-perez** [gmc-holle/xfdashboard#92]
This is a question. There is an option about notifications in xfdashboard-settings. However, notifications are not shown when xfdashboard in showing the overview. Are they supposed to do it? What is this option for?

**Comment by gmc-holle** [comment]
I think your question is if xfdashboard can show any notification also the ones send by other applications, isn't it?

No, xfdashboard shows only its own notifications not the one send by other applications. To do this xfdashboard should have to become a notification daemon also.

**Comment by alejandro-perez** [comment]
Ah, ok. I've never seen any xfdashboard notification, that's why I didn't understand at first.
I know that in case xfdashboard wanted to show notifications, it would need to implement the corresponding DBUS interface, that's why I was asking. You can only have one notification daemon (apparently), and if xfdashboard did that, I wanted to disable my other notification daemon :).
