### ISSUE TITLE
Click on icon in quicklaunch should activate running instance instead of starting new one

### ISSUE THREAD

**Issue by gmc-holle** [gmc-holle/xfdashboard#97]
Add an option to switch between the following behaviours when clicking an icon in quicklaunch:

* Start a new instance (current default action)
* Activate existing running instance

**Comment by alejandro-perez** [comment]
Makes total sense. Thanks!

**Comment by alejandro-perez** [comment]
BTW, dragging the icon should always create a new instance :)

**Comment by gmc-holle** [comment]
This behaviour is now implemented with last commit 7205d024a4d7ecdaf41c17b2269700582a8908fc

**Comment by alejandro-perez** [comment]
Thanks! I've tried it and it seems to work pretty well!

A minor issue is that, if possible, I'd rather prefer switching the active workspace to the one where the window is, instead of moving the window to the active one. 

For instance, if I have a terminal in WS 2, but I'm at WS 4 watching youtube, I'd like to click on the terminal on the left and be moved to WS 2, raising (if needed) the terminal window.

If you don't like this behaviour, just omit my comment.
Thanks anyway!!!!!

**Comment by gmc-holle** [comment]
Sorry, I haven't tested this behaviour :( And no, it wasn't intented to move the window to the current workspace. It should behave exactly the way you describe.

Should be fixed with commit 2f77e9a85ae1a865a955731542f3abafb34abf7f

**Comment by alejandro-perez** [comment]
It is, thanks!

That's an awesome response time!

Thanks again!

**Comment by axeoth** [comment]
Wow. This alone and it already deserves a release!

**Comment by alejandro-perez** [comment]
Hi,

there should be a minor error somewhere. For some reason, Kile (latex editor) is not shown in the left panel (running apps), although it is shown in the window list. See the attached snapshot. Kile is the app under the mouse pointer, but not shown on the left panel. Other KDE apps are shown, so I wonder why this particular one does not show. I does happen in daemon and non-daemon mode.

![snapshot](https://cloud.githubusercontent.com/assets/2082536/9928421/745a576a-5d26-11e5-9a46-e05711480eda.png)

**Comment by alejandro-perez** [comment]
BTW, as its current state, for me this is as usable as GNOME Shell (or even more), 100 times faster, and as stable. It has bugs, but GS does too. 

Great job, truly.

**Comment by gmc-holle** [comment]
It depends how this application was started and what informationen are provided by the system.

At the moment xfdashboard tries the following in this order:

1.) Get process ID of the window and check for enviroment variables of this process for GIO_LAUNCHED_DESKTOP_FILE and GIO_LAUNCHED_DESKTOP_FILE_PID. In addition check that the process ID stored in GIO_LAUNCHED_DESKTOP_FILE_PID matches the process ID of window. If it does the variable GIO_LAUNCHED_DESKTOP_FILE tells us the desktop file (e.g. firefox.desktop) which was used to launch this application. 
* https://github.com/gmc-holle/xfdashboard/blob/master/xfdashboard/application-tracker.c#L326

2.) Get all possible instance name for this window, e.g. class name, instance name, and check if we can find one (and only one) corresponding desktop file.
* https://github.com/gmc-holle/xfdashboard/blob/master/xfdashboard/application-tracker.c#L482
* https://github.com/gmc-holle/xfdashboard/blob/master/xfdashboard/window-tracker-window.c#L821

Yeah and sadly 1.) only works for systems running Linux. *BSD is not supported as I don't have or use any BSD system.

So if this application "Kile" is not recognized then the algorithms above fail.

Assuming (and seeing at your screenshot) that the window title contains "Kile" you could start xfdashboard in **non-daemon** mode in a terminal window, debug messages turned on and filtered to "Kile". Use the following command to get the debug message, check them for privacy and post it here. Then I could try to find out what is going wrong.

```
G_MESSAGES_DEBUG=xfdashboard xfdashboard | grep -i kile
```

**Comment by alejandro-perez** [comment]
```
(xfdashboard:6115): xfdashboard-DEBUG: Found desktop file '/usr/share/applications/kde4/kile.desktop' with desktop ID 'kde4-kile.desktop' at search path '/usr/share/applications'
(xfdashboard:6115): xfdashboard-DEBUG: Window 'erp-submission-rev1.tex – Kile' created
(xfdashboard:6115): xfdashboard-DEBUG: Enviroment set at /proc/4635/environ is 1317 bytes long for window 'erp-submission-rev1.tex – Kile'
(xfdashboard:6115): xfdashboard-DEBUG: Resolved enviroment variables of window 'erp-submission-rev1.tex – Kile' to desktop ID '<nil>'
(xfdashboard:6115): xfdashboard-DEBUG: Resolved window names of 'erp-submission-rev1.tex – Kile' to desktop ID '<nil>'
(xfdashboard:6115): xfdashboard-DEBUG: Could not resolve window 'erp-submission-rev1.tex – Kile' to any desktop ID
(xfdashboard:6115): xfdashboard-DEBUG: Could not create texture for window 'erp-submission-rev1.tex – Kile': Unable to query pixmap size
(xfdashboard:6115): xfdashboard-DEBUG: Successfully suspended live texture updates for window 'erp-submission-rev1.tex – Kile'
(xfdashboard:6115): xfdashboard-DEBUG: Resuming live texture updates for window 'erp-submission-rev1.tex – Kile'
(xfdashboard:6115): xfdashboard-DEBUG: Added window content for 'erp-submission-rev1.tex – Kile' with ref-count 1
(xfdashboard:6115): xfdashboard-DEBUG: Released resources for window 'erp-submission-rev1.tex – Kile' to handle live texture updates
(xfdashboard:6115): xfdashboard-DEBUG: Removing window content for window 'erp-submission-rev1.tex – Kile' with ref-count 1
```

**Comment by gmc-holle** [comment]
Yes, I see. Did you start "Kile" via xfdashboard or did you start it in a different way?

Anyway, both ways to resolve window names to application desktop files do not work for this application. I have another idea for a third algorithm to resolve the window to an application but it is only an idea. So far it is not easy to implement and may be error-prone :(

**Comment by alejandro-perez** [comment]
I runned it both ways, and it failed :(

Ok, I'll check it whenever it is ready, no rushes :)

Thanks!

**Comment by gmc-holle** [comment]
I think I found the reason why - at least - the second method did not recognize your application "kile" is running. But it is a different issue so I created a new issue #99 to track it and I'll keep this one closed.

**Comment by alejandro-perez** [comment]
Makes sense to me. Thanks
