### ISSUE TITLE
Application tracker does not recognize running instances from desktop files in sub-directory

### ISSUE THREAD

**Issue by gmc-holle** [gmc-holle/xfdashboard#99]
This issue was seen when starting a KDE application like Kile. The application tracker does not recognize a running instance of this application although the desktop file for it is known.

The problem is that the desktop file is located in the sub-directory "kde4" and therefore the desktop ID is named 'kde4-kile.desktop' and not 'kile.desktop'. This is the reason why the application tracker does not find the desktop file from window names (instance name etc.) because it creates the desktop ID 'kile.desktop' from these data and not 'kde4-kile.desktop'.

The application database has to be extended to also provide a list of sub-directories parsed for desktop files. The application tracker should use this list to create "extended" desktop ID (like 'kde4-kile.desktop') if the standard one (like 'kile.desktop') was not found. In addition the executed binary path could be compare to the one in the desktop file to ensure the right sub-directory was chosen but this idea also applies to the "normal" way ;)

**Comment by alejandro-perez** [comment]
Great! It seems I will see some KDE applications after all. I usually don't make use of them, but for some tasks I found out they are better than the GTK alternatives. Kile is one of these exceptions :D

**Comment by gmc-holle** [comment]
Hopefully fixed with commit e2d0b150510d275edc08ba2433d3c6b3c629aa43

It's a slightly different approach as described initially but worked in a virtual environment.

**Comment by alejandro-perez** [comment]
Hi,

I can confirm that "Kile" is shown now. Thanks!

**Comment by gmc-holle** [comment]
Great :)

Now I close this issue too
